Sea salt aerosol debromination as an option -- off by default
geoschem/geos-chem pull request #1155
Opened 2022-03-08 15:49 UTC by msulprizio

In this PR, sea salt aerosol debromination is turned off and is include as an option set in input.geos. instead. This came out of concern over benchmark where ozone concentrations are too low, especially over the Southern Ocean.

This addresses issue https://github.com/geoschem/geos-chem/issues/1145. See the discussion there for more details.

2022-03-08 15:54 UTC, msulprizio commented on KPP/fullchem/fullchem_HetStateFuncs.F90
> +       C(ind_BrSALA) = 1.0e-20_dp
Ah! Good catch. Fixing this now.

2022-03-08 15:54 UTC, yantosca requested changes
This is a straightforward fix that adds a switch to input.geos to toggle SSA debromination on or off within the heterogeneous chemistry.  Except for the typo already commented on, this is good to release.

2022-03-08 15:57 UTC, msulprizio commented on KPP/fullchem/fullchem_HetStateFuncs.F90
> +       C(ind_BrSALA) = 1.0e-20_dp
Now fixed in commit https://github.com/geoschem/geos-chem/commit/8bbe1ddccb06039be1651dca7d65214bebc6a14e.

2022-03-08 15:58 UTC, yantosca approved these changes
OK to merge pending fix of typo.

2022-03-08 22:28 UTC, msulprizio commented
This branch passes all GCClassic integration tests:

```
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 48
Execution tests failed: 0
Execution tests not yet completed: 0
```

2022-03-17 21:55 UTC, msulprizio commented
I am closing this PR. It is now superseded by #1177.

2022-03-17 21:55 UTC, closed without merging