TOMAS update
geoschem/geos-chem pull request #1378
Opened 2022-09-15 13:56 UTC by Jourdan-He

I have test run the merge on a single node simulation, and it's completed successfully.

2022-11-09 19:41 UTC, msulprizio requested changes
I recommend holding off on merging this into 14.1.0 until these comments are resolved.

2022-11-09 19:41 UTC, msulprizio commented on GeosCore/tomas_mod.F90
>      LOGICAL,   SAVE       :: FIRST = .TRUE.
These variables can be removed. They were for BPCH diagnostics code that has been commented out/removed below.

2022-11-09 19:41 UTC, msulprizio commented on GeosCore/tomas_mod.F90
> +    ! PTYPE = 7 is for ND61  --- NOW use for Nucleation at species NK1
Obsolete BPCH diagnostic code should be deleted instead of commented out to reduce clutter and avoid confusion.

2022-11-09 19:53 UTC, msulprizio commented on GeosCore/fullchem_mod.F90
> +>>>>>>> BettyFork/feature/TOMAS
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:53 UTC, msulprizio commented on GeosCore/fullchem_mod.F90
> +!#endif
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:53 UTC, msulprizio commented on GeosCore/fullchem_mod.F90
> +>>>>>>> BettyFork/feature/TOMAS
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:53 UTC, msulprizio commented on GeosCore/fullchem_mod.F90
> +>>>>>>> BettyFork/feature/TOMAS
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:54 UTC, msulprizio commented on GeosCore/tomas_mod.F90
> +       !GC(SRTSO4) = Spc(I,J,L,id_H2SO4)
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:54 UTC, msulprizio commented on GeosCore/mixing_mod.F90
> +                  State_Chm%Species(I,J,L,N) = 1.e-26_fp
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:54 UTC, msulprizio commented on GeosCore/mixing_mod.F90
> +                 !RC = GC_FAILURE !comment out to allow model to run for now -needs fix
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:54 UTC, msulprizio commented on GeosCore/mixing_mod.F90
> +                ! RC = GC_FAILURE  ! comment this out as tesst
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:54 UTC, msulprizio commented on GeosCore/mixing_mod.F90
> +             IF ( State_Chm%Species(I,J,L,N) < 0.0_fp ) THEN
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:55 UTC, msulprizio commented on GeosCore/mixing_mod.F90
> +                  State_Chm%Species(I,J,L,N) = 1.e-26_fp
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:55 UTC, msulprizio commented on GeosCore/mixing_mod.F90
> +            State_Chm%Species(Input_Opt%IFD, Input_Opt%JFD, &
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:55 UTC, msulprizio commented on GeosCore/sulfate_mod.F90
> +       !print*,'SO4OXID is ',SO4OXID, I,J,L
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:55 UTC, msulprizio commented on Headers/state_diag_mod.F90
> +     !%%%%% TOMAS microphysics rates %%%%%
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:55 UTC, msulprizio commented on Headers/state_diag_mod.F90
> +    !%%%%% Tomas microphysical rate diagnostics %%%%%
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:55 UTC, msulprizio commented on Headers/state_diag_mod.F90
> +       !--------------------------------------------------------------------
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:56 UTC, msulprizio commented on Headers/state_diag_mod.F90
> +!                diagID = 'TomasSOA'
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:56 UTC, msulprizio commented on Headers/state_diag_mod.F90
> +    CALL Finalize( diagId   = 'TomasH2SO4',                                  &
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:56 UTC, msulprizio commented on Headers/state_diag_mod.F90
> +    ELSE IF ( TRIM(Name_AllCaps) == 'TOMASH2SO4' ) THEN
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:56 UTC, msulprizio commented on Headers/state_diag_mod.F90
> +    CHARACTER(LEN=255) :: arrayID,   diagID, diagIDs(15)
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:56 UTC, msulprizio commented on Headers/state_diag_mod.F90
> +    diagIDs    = ''
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:56 UTC, msulprizio commented on GeosCore/tomas_mod.F90
> +        !  endif
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:56 UTC, msulprizio commented on GeosCore/tomas_mod.F90
> +       !IF ( ND60 > 0 ) THEN
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:57 UTC, msulprizio commented on GeosCore/tomas_mod.F90
>      LOGICAL,   SAVE       :: FIRST = .TRUE.
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:57 UTC, msulprizio commented on GeosCore/tomas_mod.F90
> +    ! PTYPE = 7 is for ND61  --- NOW use for Nucleation at species NK1
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:57 UTC, msulprizio commented on Headers/state_diag_mod.F90
> +    State_Diag%Archive_Tomas  = ( State_Diag%Archive_TomasH2SO4         .or. &
Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

2022-11-09 19:58 UTC, msulprizio commented
All but two questions/comments above have been resolved by commit Now resolved in commit [c4a3708](https://github.com/geoschem/geos-chem/pull/1378/commits/c4a37080b06dbe9c228fffce228e231ae010ccbc).

@BettyCroft also writes:

>The sulfate aqueous oxidation may not work correctly for TOMAS when using KPP until we revise the TOMAS code to deal with this process in KPP - a quick fix may be needed to keep TOMAS sims using sulfate_mod.F90 - by setting the related flag to true for TOMAS sims in Headers/state_chm_mod.F90.

2022-11-10 19:14 UTC, msulprizio commented
GCClassic integration tests are failing to compile with the TOMAS option:

```
==============================================================================
GEOS-Chem Classic: Compilation Test Results

Using 8 OpenMP threads
Number of compilation tests: 8
==============================================================================
 
Compiliation tests:
------------------------------------------------------------------------------
GCClassic........................................Configure & Build......PASS
GCClassic with APM...............................Configure & Build......PASS
GCClassic with BPCH diagnostics..................Configure & Build......PASS
GCClassic with Hg (as a KPP mechanism)...........Configure & Build......PASS
GCClassic with Luo et al wetdep..................Configure & Build......PASS
GCClassic with RRTMG.............................Configure & Build......PASS
GCClassic with TOMAS15...........................Configure & Build......FAIL
GCClassic with TOMAS40...........................Configure & Build......FAIL
 
Summary of compilation test results:
------------------------------------------------------------------------------
Complilation tests passed:        6
Complilation tests failed:        2
Complilation tests not completed: 0
```

I am looking into resolving the compilation errors now.

2022-11-14 15:41 UTC, msulprizio commented
A [fix was pushed to the HEMCO repository](https://github.com/geoschem/HEMCO/pull/164/commits/8a30947cca920be6ee1a1910b8ce58a902e05167) to resolve the TOMAS compile issue. All GCClassic simulations now pass compilation tests: 
 
 ```
 ==============================================================================
GEOS-Chem Classic: Compilation Test Results

Using 8 OpenMP threads
Number of compilation tests: 8
==============================================================================
 
Compiliation tests:
------------------------------------------------------------------------------
GCClassic........................................Configure & Build......PASS
GCClassic with APM...............................Configure & Build......PASS
GCClassic with BPCH diagnostics..................Configure & Build......PASS
GCClassic with Hg (as a KPP mechanism)...........Configure & Build......PASS
GCClassic with Luo et al wetdep..................Configure & Build......PASS
GCClassic with RRTMG.............................Configure & Build......PASS
GCClassic with TOMAS15...........................Configure & Build......PASS
GCClassic with TOMAS40...........................Configure & Build......PASS
 
Summary of compilation test results:
------------------------------------------------------------------------------
Complilation tests passed:        8
Complilation tests failed:        0
Complilation tests not completed: 0
```

TOMAS simulations are still failing the GCClassic execution tests:

```
==============================================================================
GEOS-Chem Classic: Execution Test Results

Using 24 OpenMP threads
Number of execution tests: 48
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_025x03125_CH4_geosfp_47L_na...................Execute Simulation.....PASS
...
gc_4x5_fullchem_TOMAS15_merra2_47L...............Execute Simulation.....FAIL
gc_4x5_fullchem_TOMAS40_merra2_47L...............Execute Simulation.....FAIL
...
gc_4x5_TransportTracers_merra2_LuoWd.............Execute Simulation.....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 46
Execution tests failed: 2
Execution tests not yet completed: 0
```

The issue is an error in hcox_tomas_jeagle_mod.F90.

```
HEMCO ERROR:  (A) Cannot find option Reduce SS cold water in extension          130
 --> LOCATION: GetExtOpt (hco_extlist_mod)
 
HEMCO ERROR: Error encountered in "HCOX_TOMAS_Jeagle_Init"!
 --> LOCATION:  -> at HCOX_INIT (in module HEMCO/Extensions/hcox_driver_mod.F90
===============================================================================
GEOS-Chem ERROR: Error encountered in "HCOX_Init"!
 -> at HCOI_GC_Init (in module GeosCore/hco_interface_gc_mod.F90)

THIS ERROR ORIGINATED IN HEMCO!  Please check the HEMCO log file for 
additional error messages!
===============================================================================


Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x2b912d26e3ff in ???
#1  0x2b912c411ee9 in sflush
        at ../.././libgfortran/io/unix.h:89
#2  0x638d15 in __hco_interface_gc_mod_MOD_hcoi_gc_init
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_14.1.0+TOMAS/CodeDir/src/GEOS-Chem/GeosCore/hco_interface_gc_mod.F90:664
#3  0x53f441 in __emissions_mod_MOD_emissions_init
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_14.1.0+TOMAS/CodeDir/src/GEOS-Chem/GeosCore/emissions_mod.F90:117
#4  0x4062d1 in geos_chem
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_14.1.0+TOMAS/CodeDir/src/GEOS-Chem/Interfaces/GCClassic/main.F90:732
#5  0x40bfd2 in main
        at /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_14.1.0+TOMAS/CodeDir/src/GEOS-Chem/Interfaces/GCClassic/main.F90:32
srun: error: holy7c20407: task 0: Segmentation fault (core dumped)
```

I am working on a fix.

2022-11-16 18:29 UTC, msulprizio commented
GCHP integration tests have now been updated to include TOMAS simulations. All GCHP compilation tests are passing:

```
GCHP: Compilation Test Results

Number of compilation tests: 3
==============================================================================
 
Compiliation tests:
------------------------------------------------------------------------------
GCHP.............................................Configure & Build......PASS
GCHP with TOMAS15................................Configure & Build......PASS
GCHP with TOMAS40................................Configure & Build......PASS
 
Summary of compilation test results:
------------------------------------------------------------------------------
Complilation tests passed:        3
Complilation tests failed:        0
Complilation tests not completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All compilation tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

The GCHP execution tests for TOMAS simulations are failing however:

```
==============================================================================
GCHP: Execution Test Results

Number of execution tests: 5
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_fullchem_benchmark_merra2_c48...............Execute Simulation.....PASS
gchp_fullchem_standard_merra2_c24................Execute Simulation.....PASS
gchp_fullchem_TOMAS15_merra2_c24.................Execute Simulation.....FAIL
gchp_fullchem_TOMAS40_merra2_c24.................Execute Simulation.....FAIL
gchp_TransportTracers_geosfp_c24.................Execute Simulation.....PASS
 
Summary of execution test results:
------------------------------------------------------------------------------
Execution tests passed:        3
Execution tests failed:        2
Execution tests not completed: 0
```

Further investigation is needed.

2022-11-16 18:32 UTC, msulprizio commented
The error in the GCHP TOMAS simulations is:

``` 
======================
 Contents of  CollList
  
 Tomas
 DefaultCollection
  
 
GEOS-Chem ERROR [0000]: Metadata not found for State_Diag field ID: TOMASSOANUMBER. If the
 name in HISTORY.rc has species appended, make sure the species name is preceded by a sing
le underscore. Otherwise, check that the name is listed with all capitals in subroutine Ge
t_Metadata_State_Diag (Headers/state_diag_mod.F90).
 --> LOCATION:  -> at Get_Metadata_State_Diag (in Headers/state_diag_mod.F90)
 
GEOS-Chem ERROR [0000]: Metadata not found for TomasSOAnumber_bin15 in state DIAG
 --> LOCATION: Init_HistoryExportsList (gchp_historyexports_mod.F90)
```

2022-11-17 14:26 UTC, BettyCroft commented
Hi @msulprizio and @Jourdan-He; Thanks for all your help with these TOMAS updates! I'm about to start work on the TOMAS side of things to move the TOMAS arrays out of sulfate_mod.F90 and into state_chm_mod.F90. As I'm relatively new to this work flow - could you advise me on the steps to follow to make sure that I am modifying the correct version of the code?

2022-11-17 15:59 UTC, msulprizio commented
@BettyCroft My goal is to try to get the TOMAS simulation running in GCHP so we can at least merge these update into `dev/14.1.0`. It may make sense to address the remaining science issues (raised in #1511) in a future version to avoid delaying this PR further. In any case, I think it makes sense to start the work addressing the sulfur chemistry issues off of the updates in this branch (or once they're merged into `dev/14.1.0`). I can keep you posted here once I get the TOMAS simulation at least running in GCHP.

2022-11-17 17:19 UTC, BettyCroft commented
Thanks @msulprizio, I'll also tag @theloniuspunk here so that he has an update on these developments.

2022-11-18 16:33 UTC, msulprizio commented
GCClassic integration tests are all passing except for TOMAS as well. 

```
==============================================================================
GEOS-Chem Classic: Execution Test Results

Using 24 OpenMP threads
Number of execution tests: 48
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_025x03125_CH4_geosfp_47L_na...................Execute Simulation.....PASS
gc_025x03125_fullchem_geosfp_47L_na..............Execute Simulation.....PASS
gc_05x0625_CH4_merra2_47L_na.....................Execute Simulation.....PASS
gc_05x0625_fullchem_merra2_47L_na................Execute Simulation.....PASS
gc_2x25_aerosol_merra2...........................Execute Simulation.....PASS
gc_2x25_CH4_merra2...............................Execute Simulation.....PASS
gc_2x25_CO2_merra2...............................Execute Simulation.....PASS
gc_2x25_fullchem_merra2..........................Execute Simulation.....PASS
gc_2x25_Hg_merra2................................Execute Simulation.....PASS
gc_2x25_metals_merra2............................Execute Simulation.....PASS
gc_2x25_POPs_BaP_merra2..........................Execute Simulation.....PASS
gc_2x25_tagCH4_merra2............................Execute Simulation.....PASS
gc_2x25_tagCO_merra2.............................Execute Simulation.....PASS
gc_2x25_tagO3_merra2.............................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2..................Execute Simulation.....PASS
gc_2x25_TransportTracers_merra2_LuoWd............Execute Simulation.....PASS
gc_4x5_aerosol_geosfp............................Execute Simulation.....PASS
gc_4x5_aerosol_merra2............................Execute Simulation.....PASS
gc_4x5_CH4_geosfp................................Execute Simulation.....PASS
gc_4x5_CH4_merra2................................Execute Simulation.....PASS
gc_4x5_fullchem_aciduptake_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_APM_merra2.......................Execute Simulation.....PASS
gc_4x5_fullchem_benchmark_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_merra2................Execute Simulation.....PASS
gc_4x5_fullchem_complexSOA_SVPOA_merra2..........Execute Simulation.....PASS
gc_4x5_fullchem_geosfp...........................Execute Simulation.....PASS
gc_4x5_fullchem_marinePOA_merra2.................Execute Simulation.....PASS
gc_4x5_fullchem_merra2...........................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_47L.......................Execute Simulation.....PASS
gc_4x5_fullchem_merra2_LuoWd.....................Execute Simulation.....PASS
gc_4x5_fullchem_RRTMG_merra2.....................Execute Simulation.....PASS
gc_4x5_fullchem_TOMAS15_merra2_47L...............Execute Simulation.....FAIL   <-----
gc_4x5_fullchem_TOMAS40_merra2_47L...............Execute Simulation.....FAIL   <-----
gc_4x5_Hg_geosfp.................................Execute Simulation.....PASS
gc_4x5_Hg_merra2.................................Execute Simulation.....PASS
gc_4x5_metals_merra2.............................Execute Simulation.....PASS
gc_4x5_POPs_BaP_geosfp...........................Execute Simulation.....PASS
gc_4x5_POPs_BaP_merra2...........................Execute Simulation.....PASS
gc_4x5_tagCH4_geosfp.............................Execute Simulation.....PASS
gc_4x5_tagCH4_merra2.............................Execute Simulation.....PASS
gc_4x5_tagCO_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagCO_merra2..............................Execute Simulation.....PASS
gc_4x5_tagO3_geosfp..............................Execute Simulation.....PASS
gc_4x5_tagO3_merra2..............................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp...................Execute Simulation.....PASS
gc_4x5_TransportTracers_geosfp_LuoWd.............Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2...................Execute Simulation.....PASS
gc_4x5_TransportTracers_merra2_LuoWd.............Execute Simulation.....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 46
Execution tests failed: 2
Execution tests not yet completed: 0
```

The TOMAS simulations are failing with the following error in the GEOS-Chem log file:

```
At line 6340 of file /n/holyscratch01/jacob_lab/msulprizio/GC/rundirs/IntTest_GCC_14.1.0_TOMAS/CodeDir/src/GEOS-Chem/GeosCore/tomas_mod.F90
Fortran runtime error: Index '2' of dimension 4 of array 'state_diag%tomasmnfixcheck3mass' above upper bound of 1
```

2022-12-20 18:31 UTC, BettyCroft commented
Hi @msulprizio and @Jourdan-He  - I have just submitted a pull request for the bug fix for TOMAS sulfate production rates. Not sure that I named it all that well - it is called Feature/tomaswork and #1569

2023-04-07 13:54 UTC, msulprizio commented
This has now been merged into dev/14.2.0.

2023-04-07 13:54 UTC, closed without merging

2023-04-07 14:02 UTC, BettyCroft commented
Hi @msulprizio, Thank you for all your work with this PR.

2023-04-07 15:33 UTC, theloniuspunk commented
Thanks, Melissa!

On Fri, Apr 7, 2023, 8:02 AM BettyCroft ***@***.***> wrote:

> Hi @msulprizio <https://github.com/msulprizio>, Thank you for all your
> work with this PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/geoschem/geos-chem/pull/1378#issuecomment-1500317994>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQBKQDXRUQ25WBU3XHISS2DXAAM7LANCNFSM6AAAAAAQNNQ4P4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>