Initialize CO2 to reasonable value instead of zero in fullchem_mod.F90
geoschem/geos-chem pull request #1603
Opened 2023-01-17 17:28 UTC by msulprizio

As discussed in https://github.com/geoschem/geos-chem/issues/1529, the code to reset CO2 to zero at every timestep should not be used. Instead, @msl3v recommends setting CO2 to an appropriate ambient value (400 ppm).

Closes #1529.

2023-01-17 18:00 UTC, yantosca requested changes
OK to merge after units are confirmed

2023-01-17 19:43 UTC, msulprizio commented on GeosCore/fullchem_mod.F90
> +          State_Chm%Species(N)%Conc(:,:,:) = 400.0e-6_fp ! v/v
Yes, they are indeed in `kg`. Thanks for catching that. I will push a fix.

2023-01-18 13:23 UTC, msulprizio commented on GeosCore/fullchem_mod.F90
> +          State_Chm%Species(N)%Conc(:,:,:) = 400.0e-6_fp ! v/v
I tried converting 400 ppb to kg within the code but got KPP errors.

2023-01-18 13:23 UTC, msulprizio commented
A better fix is needed here. I will close out this PR for now.

2023-01-18 13:23 UTC, closed without merging