GCHP bug fixes and run directory updates
geoschem/geos-chem pull request #1724
Opened 2023-03-24 19:03 UTC by lizziel

### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Confirm you have reviewed the following documentation

- [X] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### Describe the update

This PR includes the following GCHP updates:

1. Example grid labels are now commented out in all HISTORY.rc files by default. This avoids a decomposition problem if running with over 3000 cores since grids are created for all uncommented grid labels regardless of whether they are used in a collection.

2. The interactive run script now prints error messages to screen in addition to the log, and also stops if an error is encountered. Previously some error messages were only written to log and the script kept going if an error was encountered, such as a non-existent restart file.

3. Simulations that require all species in the GC-Classic restart file, e.g. standard fullchem, now also require all species in the GCHP restart file. A new toggle in `setCommonRunSettings.sh` allows changing this behavior. Like GC-Classic, all simulations allow missing species during integration testing.

4. Overwriting existing GCHP diagnostic files is allowed again after not working since 14.0 when MAPL was updated. The behavior is now controlled from a switch at the top of `HISTORY.rc`.

5. All GCHP checkpoint files are now written directly to the `Restarts` folder in the run directory. This avoids writing large files locally if necessary since the `Restarts` folder can be symbolically linked to a different drive.

6. All GCHP checkpoint files are now renamed to the standard GEOS-Chem restart filename format, with the exception of the checkpoint file for the start time. That file is deleted so as not to overwrite the original restart file of the run.

### Expected changes

This update is zero diff for all simulation diagnostics and restart file content. Changes are limited to run behavior. It is now possible to:
1. allow overwriting diagnostics files
2. restart GCHP directly from an output checkpoint file generated in the middle of a run
3. run GCHP with >3000 cores
4. better detect run directory problems such as missing restart file
5. force the model to crash if a species is missing from the restart file
6. write all restart files directly to the Restarts subdirectory

### Reference(s)

None

### Related Github Issue(s)

https://github.com/geoschem/GCHP/issues/303
https://github.com/geoschem/GCHP/issues/300
https://github.com/geoschem/GCHP/issues/296
https://github.com/geoschem/GCHP/issues/295
https://github.com/geoschem/geos-chem/issues/1412

2023-03-28 15:35 UTC, lizziel commented
Integration tests pass. Difference tests in progress.

2023-03-28 16:25 UTC, yantosca approved these changes
These updates all look good.  OK to merge

2023-03-28 18:38 UTC, msulprizio requested changes
I've requested one small change in the comments for `ExtData.rc.templates.carbon`.

2023-03-28 18:38 UTC, msulprizio commented on run/GCHP/ExtData.rc.templates/ExtData.rc.carbon
>  # ** TODO: Update to 14.0.0 **
Can we remove these TODO lines since this is now done?

2023-03-28 18:48 UTC, msulprizio approved these changes

2023-03-28 20:13 UTC, yantosca approved these changes

2023-03-30 15:32 UTC, lizziel commented
I just realized this update will require an update to the gc-cloud-infrastructure in in this [file](https://github.com/geoschem/gc-cloud-infrastructure/blob/main/benchmarks/scripts/stages/runGCHP.sh) since the restart file is now written directly to Restarts rather than being moved there. I will make a separate PR for that. Is this going to cause problems with benchmarking?

2023-03-30 18:12 UTC, msulprizio commented
> Is this going to cause problems with benchmarking?

@lizziel I don't believe this will cause an issue with benchmarking. I will try to merge both concurrently to avoid issues.

2023-03-30 20:29 UTC, lizziel commented
This PR should be merged at the same time as https://github.com/geoschem/gc-cloud-infrastructure/pull/44 to avoid cloud benchmarking issues.

2023-04-04 00:15 UTC, merged