move REF_TRF file from OtherAnthropogenic to Oil
geoschem/geos-chem pull request #1856
Opened 2023-06-29 15:35 UTC by nicholasbalasus

### Name and Institution (Required)

Name: Nick Balasus
Institution: Harvard University

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### Describe the update

Currently, for the default HEMCO configuration for the CH4 simulation (ignoring regional inventories), GFEIv2 is used for Oil, Gas, and Coal and all other anthropogenic emissions come from EDGAR. One of our included Other Anthropogenic files from EDGAR is REF_TRF (Oil refineries and Transformation Industry, IPCC 2006 codes of 1A1b+1A1ci+1A1cii+1A5biii+1B1b+1B2aiii6+1B2biii3+1B1c). [GFEIv2](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HH4EUM) includes all 1B1 and 1B2 sector emissions, meaning that including REF_TRF is (partially) double counting. I suggest we move it into the EDGAR Oil emissions category so it is superseded by GFEIv2 Oil.

### Expected changes

A reduction of CH4 emissions by a few Tg/Yr (~6 Tg/yr globally for 2018 with EDGAR v6 while ignoring regional inventories).

### Reference(s)

n/a

### Related Github Issue(s)

https://github.com/geoschem/geos-chem/issues/1855

2023-06-30 14:29 UTC, msulprizio requested changes
Thanks @nicholasbalasus. We should also apply this fix to HEMCO_Config.rc.tagCH4 and HEMCO_Config.rc.carbon (for GCClassic and GCHP) and update CHANGELOG.md accordingly. Would you mind doing this in your branch so it's updated in this pull request?

2023-06-30 14:52 UTC, nicholasbalasus commented
Got it now, thanks!

2023-06-30 14:53 UTC, msulprizio approved these changes

2023-07-07 16:58 UTC, yantosca commented
After merging these changes on top of PR #1799, all GEOS-Chem integration tests passed (except for TOMAS, which is a known issue that will be fixed later).
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #dae6c49 GEOS-Chem submod update: PR #1799 (Explicitly define tagCH4 sims)
GEOS-Chem #967e90e14 Move EDGAR_REF_TRF_CH4 emissions to the Oil category for CH4/carbon sims
HEMCO     #faaddbb Merge PR #220 (branch 'feature/add_geosit_as_met_option') into dev/3.7.0

Using 24 OpenMP threads
Number of execution tests: 26

Submitted as SLURM job: 61603248
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_05x0625_NA_47L_merra2_CH4........................Execute Simulation....PASS
gc_05x0625_NA_47L_merra2_fullchem...................Execute Simulation....PASS
gc_4x5_47L_merra2_fullchem..........................Execute Simulation....PASS
gc_4x5_47L_merra2_fullchem_TOMAS15..................Execute Simulation....FAIL
gc_4x5_47L_merra2_fullchem_TOMAS40..................Execute Simulation....FAIL
gc_4x5_merra2_aerosol...............................Execute Simulation....PASS
gc_4x5_merra2_carbon................................Execute Simulation....PASS
gc_4x5_merra2_CH4...................................Execute Simulation....PASS
gc_4x5_merra2_CO2...................................Execute Simulation....PASS
gc_4x5_merra2_fullchem..............................Execute Simulation....PASS
gc_4x5_merra2_fullchem_aciduptake...................Execute Simulation....PASS
gc_4x5_merra2_fullchem_APM..........................Execute Simulation....PASS
gc_4x5_merra2_fullchem_benchmark....................Execute Simulation....PASS
gc_4x5_merra2_fullchem_complexSOA...................Execute Simulation....PASS
gc_4x5_merra2_fullchem_complexSOA_SVPOA.............Execute Simulation....PASS
gc_4x5_merra2_fullchem_LuoWd........................Execute Simulation....PASS
gc_4x5_merra2_fullchem_marinePOA....................Execute Simulation....PASS
gc_4x5_merra2_fullchem_RRTMG........................Execute Simulation....PASS
gc_4x5_merra2_Hg....................................Execute Simulation....PASS
gc_4x5_merra2_metals................................Execute Simulation....PASS
gc_4x5_merra2_POPs_BaP..............................Execute Simulation....PASS
gc_4x5_merra2_tagCH4................................Execute Simulation....PASS
gc_4x5_merra2_tagCO.................................Execute Simulation....PASS
gc_4x5_merra2_tagO3.................................Execute Simulation....PASS
gc_4x5_merra2_TransportTracers......................Execute Simulation....PASS
gc_4x5_merra2_TransportTracers_LuoWd................Execute Simulation....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 24
Execution tests failed: 2
Execution tests not yet completed: 0
```
Furthermore, most integration tests were identical to PR #1799.  The exceptions being:
- carbon, CH4, tagCH4 (differences introduced in this PR to avoid double-counting emissions)
- APM, Hg, fullchem_LuoWd, TOMAS (these have parallelization issues as described in #1682)
```console
Checking gc_05x0625_NA_47L_merra2_CH4
   -> 4 differences found in OutputDir
      * GCC_14.2.1_r4/rundirs/gc_05x0625_NA_47L_merra2_CH4/OutputDir/GEOSChem.CH4.20190101_0000z.nc4 
        GCC_14.2.1_r5/rundirs/gc_05x0625_NA_47L_merra2_CH4/OutputDir/GEOSChem.CH4.20190101_0000z.nc4 
      * GCC_14.2.1_r4/rundirs/gc_05x0625_NA_47L_merra2_CH4/OutputDir/GEOSChem.Metrics.20190101_0000z.nc4 
        GCC_14.2.1_r5/rundirs/gc_05x0625_NA_47L_merra2_CH4/OutputDir/GEOSChem.Metrics.20190101_0000z.nc4 
      * GCC_14.2.1_r4/rundirs/gc_05x0625_NA_47L_merra2_CH4/OutputDir/GEOSChem.SpeciesConc.20190101_0000z.nc4 
        GCC_14.2.1_r5/rundirs/gc_05x0625_NA_47L_merra2_CH4/OutputDir/GEOSChem.SpeciesConc.20190101_0000z.nc4 
      * GCC_14.2.1_r4/rundirs/gc_05x0625_NA_47L_merra2_CH4/OutputDir/HEMCO_diagnostics.201901010000.nc 
        GCC_14.2.1_r5/rundirs/gc_05x0625_NA_47L_merra2_CH4/OutputDir/HEMCO_diagnostics.201901010000.nc 
   -> 1 difference found in Restarts
      * GCC_14.2.1_r4/rundirs/gc_05x0625_NA_47L_merra2_CH4/Restarts/GEOSChem.Restart.20190101_0020z.nc4 
        GCC_14.2.1_r5/rundirs/gc_05x0625_NA_47L_merra2_CH4/Restarts/GEOSChem.Restart.20190101_0020z.nc4 

Checking gc_05x0625_NA_47L_merra2_fullchem
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_47L_merra2_fullchem
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_47L_merra2_fullchem_TOMAS15
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_47L_merra2_fullchem_TOMAS40
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_aerosol
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_carbon
   -> 2 differences found in OutputDir
      * GCC_14.2.1_r4/rundirs/gc_4x5_merra2_carbon/OutputDir/GEOSChem.SpeciesConc.20190101_0000z.nc4 
        GCC_14.2.1_r5/rundirs/gc_4x5_merra2_carbon/OutputDir/GEOSChem.SpeciesConc.20190101_0000z.nc4 
      * GCC_14.2.1_r4/rundirs/gc_4x5_merra2_carbon/OutputDir/HEMCO_diagnostics.201901010000.nc 
        GCC_14.2.1_r5/rundirs/gc_4x5_merra2_carbon/OutputDir/HEMCO_diagnostics.201901010000.nc 
   -> 1 difference found in Restarts
      * GCC_14.2.1_r4/rundirs/gc_4x5_merra2_carbon/Restarts/GEOSChem.Restart.20190101_0100z.nc4 
        GCC_14.2.1_r5/rundirs/gc_4x5_merra2_carbon/Restarts/GEOSChem.Restart.20190101_0100z.nc4 

Checking gc_4x5_merra2_CH4
   -> 4 differences found in OutputDir
      * GCC_14.2.1_r4/rundirs/gc_4x5_merra2_CH4/OutputDir/GEOSChem.CH4.20190101_0000z.nc4 
        GCC_14.2.1_r5/rundirs/gc_4x5_merra2_CH4/OutputDir/GEOSChem.CH4.20190101_0000z.nc4 
      * GCC_14.2.1_r4/rundirs/gc_4x5_merra2_CH4/OutputDir/GEOSChem.Metrics.20190101_0000z.nc4 
        GCC_14.2.1_r5/rundirs/gc_4x5_merra2_CH4/OutputDir/GEOSChem.Metrics.20190101_0000z.nc4 
      * GCC_14.2.1_r4/rundirs/gc_4x5_merra2_CH4/OutputDir/GEOSChem.SpeciesConc.20190101_0000z.nc4 
        GCC_14.2.1_r5/rundirs/gc_4x5_merra2_CH4/OutputDir/GEOSChem.SpeciesConc.20190101_0000z.nc4 
      * GCC_14.2.1_r4/rundirs/gc_4x5_merra2_CH4/OutputDir/HEMCO_diagnostics.201901010000.nc 
        GCC_14.2.1_r5/rundirs/gc_4x5_merra2_CH4/OutputDir/HEMCO_diagnostics.201901010000.nc 
   -> 1 difference found in Restarts
      * GCC_14.2.1_r4/rundirs/gc_4x5_merra2_CH4/Restarts/GEOSChem.Restart.20190101_0100z.nc4 
        GCC_14.2.1_r5/rundirs/gc_4x5_merra2_CH4/Restarts/GEOSChem.Restart.20190101_0100z.nc4 

Checking gc_4x5_merra2_CO2
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_fullchem
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_fullchem_aciduptake
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gc_4x5_merra2_fullchem_APM
   -> 3 differences found in OutputDir
      * GCC_14.2.1_r4/rundirs/gc_4x5_merra2_fullchem_APM/OutputDir/GEOSChem.Metrics.20190701_0000z.nc4 
        GCC_14.2.1_r5/rundirs/gc_4x5_merra2_fullchem_APM/OutputDir/GEOSChem.Metrics.20190701_0000z.nc4 
      * GCC_14.2.1_r4/rundirs/gc_4x5_merra2_fullchem_APM/OutputDir/GEOSChem.SpeciesConc.20190701_0000z.nc4 
        GCC_14.2.1_r5/rundirs/gc_4x5_merra2_fullchem_APM/OutputDir/GEOSChem.SpeciesConc.20190701_0000z.nc4 
      * GCC_14.2.1_r4/rundirs/gc_4x5_merra2_fullchem_APM/OutputDir/HEMCO_diagnostics.201907010000.nc 
        GCC_14.2.1_r5/rundirs/gc_4x5_merra2_fullchem_APM/OutputDir/HEMCO_diagnostics.201907010000.nc 
   -> 1 difference found in Restarts
      * GCC_14.2.1_r4/rundirs/gc_4x5_merra2_fullchem_APM/Restarts/GEOSChem.Restart.20190701_0100z.nc4 
        GCC_14.2.1_r5/rundirs/gc_4x5_ [...]

2023-07-07 17:02 UTC, yantosca commented
After merging these changes on top of PR https://github.com/geoschem/geos-chem/pull/1799, all GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCClassic #0711a9d HEMCO submod update: Merge PR #215 (plus post-fixes)
GEOS-Chem #967e90e14 Move EDGAR_REF_TRF_CH4 emissions to the Oil category for CH4/carbon sims
HEMCO     #24cf7e0 PR #215 post-merge fixes: Update CHANGELOG.md & version numbers

Number of execution tests: 5

Submitted as SLURM job: 61603265
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_merra2_fullchem................................Execute Simulation....PASS
gchp_merra2_fullchem_benchmark......................Execute Simulation....PASS
gchp_merra2_fullchem_RRTMG..........................Execute Simulation....PASS
gchp_merra2_tagO3...................................Execute Simulation....PASS
gchp_merra2_TransportTracers........................Execute Simulation....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 5
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
and all GCHP integration tests were identical to PR #1799.
```console
Checking gchp_merra2_fullchem
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gchp_merra2_fullchem_benchmark
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gchp_merra2_fullchem_RRTMG
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gchp_merra2_tagO3
   -> No differences in OutputDir
   -> No differences in Restarts

Checking gchp_merra2_TransportTracers
   -> No differences in OutputDir
   -> No differences in Restarts
```

2023-07-07 17:07 UTC, merged

2023-07-07 17:12 UTC, nicholasbalasus commented
Thank you @yantosca!