[WIP] Add capability to run GEOS-Chem at 0.125x0.15625 resolution
geoschem/geos-chem pull request #1980
Opened 2023-10-06 14:31 UTC by msulprizio

### Name and Institution (Required)

Name: Melissa Sulprizio
Institution: Harvard / GCST

### Describe the update

NASA GMAO has provided 1-hourly mass flux fields for GEOS-FP meteorology at c720 resolution to drive GCHP. The mass flux fields have been converted to derived winds fields and further regridded from c720 to 0.125x0.15625 lat-lon resolution. The new files include the following collections and met fields:
    
- `GEOS.fp.asm.I1dyn` : PS, SPHU
- `GEOS.fp.asm.A1dyn` : U, V

So far only run directory files have been updated in this PR. The script `createRunDir.sh` has been updated to include this resolution as an option when running with GEOS-FP meteorology. The use of this resolution and these fields is still being evaluated for it's impact on model output and performance.

### Expected changes

This update will not impact the full-chemistry benchmark simulations which are run at 4x5 resolution.

### Related Github Issue(s)

- https://github.com/geoschem/integrated_methane_inversion/issues/62

2024-04-21 14:44 UTC, msulprizio commented
There seems to be an issue in input_mod.F90 cutting off the longitude resolution string to 4 decimal places and changing 0.15625 to 0.1563. This causes differences in the longitude edge and center values saved to netCDF output. I will push a fix shortly and post difference plots to show the impact on model output.

Tagging @xlwangg

2024-04-22 18:36 UTC, msulprizio commented
The above issue in the longitude string length was already fixed by @xlwangg and is now also fixed in commit https://github.com/geoschem/geos-chem/pull/1980/commits/cb71dfac542a0a95b0f3e558933f6634a7199204

2025-03-26 16:13 UTC, msulprizio commented
Integration tests for 0.125x0.15625 NA GEOS-FP CH4 simulations have been added. All GCClassic integration tests, including this new one, are passing:

```
==============================================================================
GEOS-Chem Classic: Execution Test Results

CodeDir   : de146f8 GEOS-Chem update: Merge PR #2779 (Add SatDiagnPMID diag)
GEOS-Chem : a6506ec53 Add 0.125x0.15625 CH4 simulation to integration tests and fixes to get all tests to pass
HEMCO     : d09c9aa Merge branch 'dev/3.11.0' into feature/0.125x0.15625_resolution
Cloud-J   : 2b111a4 Merge pull request #29 from geoschem/feature/return_arrays_for_uvflux_diagnostics
HETP      : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Using 24 OpenMP threads
Number of execution tests: 42

Submitted as SLURM job: 8074421
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gc_0125x015625_NA_geosfp_CH4........................Execute Simulation....PASS
gc_025x03125_NA_geosfp_CH4..........................Execute Simulation....PASS
gc_05x0625_NA_merra2_CH4............................Execute Simulation....PASS
gc_2x25_ModelE2.1_fullchem..........................Execute Simulation....PASS
gc_4x5_47L_merra2_fullchem..........................Execute Simulation....PASS

...
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 42
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

2025-03-26 18:43 UTC, yantosca requested changes
Thanks for the update @msulprizio.  I've noted a few things (mostly minor).

2025-03-27 16:41 UTC, msulprizio commented on CHANGELOG.md
> +- Added option to run GEOS-Chem at 0.125x0.15625 resolution using GEOS-FP derived winds fields generated from c720 mass fluxes archived by GMAO
Now fixed in https://github.com/geoschem/geos-chem/pull/1980/commits/eaa68f13d0286627d213912c2ee28536d71afd71

2025-03-27 16:41 UTC, msulprizio commented on GeosCore/flexgrid_read_mod.F90
> +!                                                                             .
Now removed in https://github.com/geoschem/geos-chem/pull/1980/commits/eaa68f13d0286627d213912c2ee28536d71afd71.

2025-03-27 16:41 UTC, msulprizio commented on GeosCore/flexgrid_read_mod.F90
> +!  Special handling for surface precipitation fields:
Now removed in https://github.com/geoschem/geos-chem/pull/1980/commits/eaa68f13d0286627d213912c2ee28536d71afd71

2025-03-27 16:41 UTC, msulprizio commented on GeosCore/flexgrid_read_mod.F90
> +    IF ( TRIM(State_Grid%GridRes) .NE. '0.125x0.15625' ) THEN
Now fixed in https://github.com/geoschem/geos-chem/pull/1980/commits/eaa68f13d0286627d213912c2ee28536d71afd71

2025-03-27 16:42 UTC, msulprizio commented on GeosCore/flexgrid_read_mod.F90
> +!  This routine was automatically generated by the Perl script ncCodeRead,
Now removed in https://github.com/geoschem/geos-chem/pull/1980/commits/eaa68f13d0286627d213912c2ee28536d71afd71

2025-03-27 16:42 UTC, msulprizio commented on GeosCore/flexgrid_read_mod.F90
> +    IF ( TRIM(State_Grid%GridRes) .NE. '0.125x0.15625' ) THEN
Now fixed in https://github.com/geoschem/geos-chem/pull/1980/commits/eaa68f13d0286627d213912c2ee28536d71afd71

2025-03-27 16:42 UTC, msulprizio commented on GeosCore/flexgrid_read_mod.F90
> +    IF ( TRIM(State_Grid%GridRes) .NE. '0.125x0.15625' ) THEN
Now fixed in https://github.com/geoschem/geos-chem/pull/1980/commits/eaa68f13d0286627d213912c2ee28536d71afd71

2025-03-27 16:42 UTC, msulprizio commented on GeosCore/flexgrid_read_mod.F90
> +!  This routine was automatically generated by the Perl script ncCodeRead,
Now removed in https://github.com/geoschem/geos-chem/pull/1980/commits/eaa68f13d0286627d213912c2ee28536d71afd71

2025-03-27 16:42 UTC, msulprizio commented on GeosCore/sulfate_mod.F90
> +    !   TSCALE = 0.25*3600.
Now fixed in https://github.com/geoschem/geos-chem/pull/1980/commits/eaa68f13d0286627d213912c2ee28536d71afd71

2025-03-27 16:42 UTC, msulprizio commented on GeosCore/tomas_mod.F90
> +    !   SGCTSCALE = 0.25*3600.
Now fixed in https://github.com/geoschem/geos-chem/pull/1980/commits/eaa68f13d0286627d213912c2ee28536d71afd71

2025-03-27 16:42 UTC, msulprizio commented on GeosUtil/time_mod.F90
> +    ENDIF
Now fixed in https://github.com/geoschem/geos-chem/pull/1980/commits/eaa68f13d0286627d213912c2ee28536d71afd71

2025-03-27 16:43 UTC, msulprizio commented on run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.gmao_metfields_0125
> +#==============================================================================
Added a comment in https://github.com/geoschem/geos-chem/pull/1980/commits/eaa68f13d0286627d213912c2ee28536d71afd71

2025-03-27 16:44 UTC, msulprizio commented on test/integration/GCClassic/integrationTestCreate.sh
> +    create_rundir "9\n2\ny\n5\n4\n1\n${rundirsDir}\n\nn\n" "${log}"
Yes, I removed the fullchem nested-grid test because we already had the CH4 nested-grid tests at 0.5x0.625, 0.25x0.3125, and 0.125x0.15625 resolutions. It wasn't clear to me that the fullchem nested-grid test would provide information that the CH4 simulations would not and removing it should speed up integration testing.

2025-03-27 16:45 UTC, msulprizio commented on GeosCore/hco_interface_gc_mod.F90
> +      IF ( TRIM(State_Grid%GridRes) .NE. '0.125x0.15625' ) THEN
Now resolved in https://github.com/geoschem/geos-chem/pull/1980/commits/a0c51fe9cabfdec3fb969dd52ff8587beebc0d8c

2025-03-27 16:46 UTC, msulprizio commented on GeosCore/hco_interface_gc_mod.F90
> +          CALL AvgPole( State_Grid, State_Met%PS1_DRY )
This code mimics code already in place for other resolutions. If it needs to be removed, perhaps that's better done in a separate PR?

2025-03-27 17:11 UTC, lizziel commented on GeosCore/hco_interface_gc_mod.F90
> +          CALL AvgPole( State_Grid, State_Met%PS1_DRY )
The pole averaging that affects CESM is in the map_a2a regridding and not reading met-fields. In CESM we don't read the met files but get meteorology from elsewhere in the model.

2025-03-27 17:11 UTC, lizziel commented on GeosCore/hco_interface_gc_mod.F90
> +          CALL AvgPole( State_Grid, State_Met%PS2_DRY )
Same comment as above.

2025-03-27 17:37 UTC, yantosca commented on GeosCore/hco_interface_gc_mod.F90
> +          CALL AvgPole( State_Grid, State_Met%PS1_DRY )
Thanks @lizziel.  Then we can resolve this conversation.

2025-03-27 17:43 UTC, yantosca approved these changes
Thanks @msulprizio and @lizziel.  This is good to merge.

2025-03-27 18:43 UTC, lizziel requested changes

2025-03-27 18:43 UTC, lizziel commented on CHANGELOG.md
> +- Added option to run GEOS-Chem at 0.125x0.15625 resolution using GEOS-FP derived winds fields generated from c720 mass fluxes archived by GMAO
I suggest updating this to read "GEOS-Chem Classic" and specify it is for running nested simulations only. The PR description should be clear about this to to avoid confusion.

2025-03-27 20:11 UTC, yantosca commented on CHANGELOG.md
> +- Added option to run GEOS-Chem at 0.125x0.15625 resolution using GEOS-FP derived winds fields generated from c720 mass fluxes archived by GMAO
I updated the name of the PR accordingly.  @msulprizio: can you change this in the CHANGELOG.md?

2025-03-27 21:14 UTC, lizziel approved these changes

2025-03-27 21:45 UTC, merged

2025-03-27 21:47 UTC, msulprizio commented on CHANGELOG.md
> +- Added option to run GEOS-Chem at 0.125x0.15625 resolution using GEOS-FP derived winds fields generated from c720 mass fluxes archived by GMAO
Thanks for catching that. I modified that line in the merge commit [d74abd6](https://github.com/geoschem/geos-chem/commit/d74abd6d890195a867db22a6fc6a5f7e1210bf57).