Fix PBL level calculations
geoschem/geos-chem pull request #2078
Opened 2023-12-19 03:14 UTC by cdholmes

@lizziel, This is a PR for the PBL level fix only, as you requested.

Use local scale height and level thickness to determine PBL top level and pressure thickness. The code previously used a fixed global value for scale height, which is too large near poles and too small in tropics. This update lowers the PBL top level in the tropics and raises it near the poles. The change is typically 1 model level or less.

### Name and Institution (Required)

Name: Chris Holmes
Institution: FSU

### Related Github Issue(s)

See #2002 for the expected impact of this change on PBL heights: typically no more than 1 model level up or down.

2023-12-19 15:44 UTC, lizziel requested changes
Thanks @cdholmes. I made a few comments with minor code changes.

2023-12-19 15:44 UTC, lizziel commented on GeosCore/pbl_mix_mod.F90
> +    REAL(fp) :: BLTOP,  BLTHIK, DELP, Lower_Edge_Height
Remove BLTOP, BLTHIK, and DELP since no longer used.

2023-12-19 15:44 UTC, lizziel commented on GeosCore/pbl_mix_mod.F90
> +    !$OMP PRIVATE( I, J, L, P, BLTOP, BLTHIK, LTOP, DELP ) &
Remove BLTOP, BLTHIK, and DELP since no longer used.

2023-12-19 15:44 UTC, lizziel commented on GeosCore/pbl_mix_mod.F90
> +       Lower_Edge_Height = 0d0
Use 0.0_fp since variable is declared with flexible precision.

2023-12-19 15:44 UTC, lizziel commented on GeosCore/pbl_mix_mod.F90
> +            State_Met%F_Under_PBLTop(I,J,L) = 1.0d0
Use 1.0_fp since variable is flexible precision.

2023-12-19 15:44 UTC, lizziel commented on GeosCore/pbl_mix_mod.F90
> +    FPBL    = State_Met%PBL_Top_L - (IMIX-1) ! Fractional level above IMIX to PBL top
Declaration of IMIX and FPBL need to be changed from pointers to arrays earlier in the subroutine.

2024-03-19 20:28 UTC, lizziel approved these changes

2024-03-21 16:52 UTC, yantosca commented
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #6607cae GEOS-Chem submod update: Merge PR #2205 (Fix uptake on strat aer)
GEOS-Chem #a1359ddc1 Merge PR #2078 (Fix PBL level calculations)
HEMCO     #f807e1a Update HEMCO version number to 3.8.0 in preparation for release

Using 24 OpenMP threads
Number of execution tests: 26

Submitted as SLURM job: 24589366
==============================================================================
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
All GCHP execution tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #d60a8e9 GEOS-Chem submod update: Merge PR #2205 (Fix uptake on strat aer)
GEOS-Chem #a1359ddc1 Merge PR #2078 (Fix PBL level calculations)
HEMCO     #f807e1a Update HEMCO version number to 3.8.0 in preparation for release

Number of execution tests: 6

Submitted as SLURM job: 24592207
==============================================================================
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

2024-03-21 16:52 UTC, merged

2024-03-21 20:51 UTC, yantosca commented
@cdholmes @msulprizio @lizziel: The GCClassic 14.4.0-alpha.8 1-month benchmark died with this error:
```console
********************************************
* B e g i n   T i m e   S t e p p i n g !! *
********************************************

---> DATE: 2019/07/01  UTC: 00:00
 HEMCO already called for this timestep. Returning.
 Getting CH4 boundary conditions in GEOS-Chem from :NOAA_GMD_CH4
HEMCO (VOLCANO): Opening /ExtData/HEMCO/VOLCANO/v2024-03/so2_volcanic_emissions_CARN_v202106.degassing_only.rc
     - DO_LINEAR_CHEM: Linearized chemistry at 2019/07/01 00:00
     - LINOZ_CHEM3: Doing LINOZ
---> DATE: 2019/07/01  UTC: 00:10
---> DATE: 2019/07/01  UTC: 00:20
     - DO_LINEAR_CHEM: Linearized chemistry at 2019/07/01 00:20
     - LINOZ_CHEM3: Doing LINOZ
---> DATE: 2019/07/01  UTC: 00:30
---> DATE: 2019/07/01  UTC: 00:40
     - DO_LINEAR_CHEM: Linearized chemistry at 2019/07/01 00:40
     - LINOZ_CHEM3: Doing LINOZ
---> DATE: 2019/07/01  UTC: 00:50
---> DATE: 2019/07/01  UTC: 01:00
     - Found all A1     met fields for 2019/07/01 01:30
 bad sum at:            1          43
 bad sum at:           27          18
 bad sum at:           40          24
 bad sum at:           15          34
 bad sum at:           34          27
 bad sum at:           18          28
 bad sum at:           42          27
 bad sum at:            1           2
 bad sum at:           14          31
 bad sum at:            3          10
 bad sum at:            2          41
 bad sum at:           17          39
 bad sum at:            4          43
 bad sum at:           13           7
 bad sum at:           59           8
 bad sum at:           21          34
 bad sum at:           15          33
 bad sum at:           43          16
 bad sum at:            1          45
 bad sum at:           12          38
 bad sum at:            5          43
 bad sum at:            2           2
 bad sum at:           20           5
 bad sum at:           20           4
 bad sum at:           25          15
 bad sum at:           21           4
 bad sum at:           17          43
 bad sum at:           16          33
 bad sum at:           23           6
 bad sum at:           21          22
 bad sum at:           15          11
 bad sum at:            7          40
 bad sum at:           17          33
 bad sum at:           26           4
 bad sum at:           43          22
 bad sum at:            7          37
 bad sum at:           28          18
 bad sum at:            3           2
 bad sum at:           15          12
 bad sum at:           40          10
 bad sum at:           14          30
 bad sum at:           35          26
 bad sum at:           25          17
 bad sum at:           39          26
 bad sum at:           40           6
 bad sum at:           18          33
 bad sum at:           22          34
 bad sum at:           13          37
 bad sum at:           17          38
 bad sum at:           21           2
 bad sum at:           17          32
 bad sum at:           17          31
 bad sum at:           29          45
 bad sum at:           43          23
 bad sum at:           41          18
 bad sum at:           22           5
 bad sum at:           16          29
 bad sum at:           23          34
 bad sum at:           19          31
 bad sum at:           18          32
 bad sum at:           20          31
 bad sum at:           23          14
 bad sum at:           44          22
 bad sum at:            3           9
 bad sum at:           37          34
 bad sum at:            1          35
 bad sum at:           68          34
 bad sum at:           21          31
 bad sum at:            4           9
 bad sum at:           34           4
 bad sum at:           30          45
 bad sum at:           16           7
 bad sum at:           21          44
 bad sum at:           31           7
 bad sum at:           25          44
 bad sum at:           36           7
 bad sum at:           26          44
 bad sum at:           44           7
 bad sum at:           32          44
 bad sum at:           35           4
 bad sum at:           12          35
 bad sum at:           20          43
 bad sum at:           42          18
 bad sum at:           15          35
 bad sum at:           24          21
 bad sum at:           16          35
 bad sum at:           19          28
 bad sum at:           19          33
 bad sum at:           31          45
 bad sum at:           20          33
 bad sum at:           23          39
 bad sum at:           14          41
 bad sum at:           34          28
 bad sum at:           18          41
 bad sum at:           39           4
 bad sum at:            1          36
 bad sum at:           25          38
 bad sum at:           17          29
 bad sum at:           29          21
 bad sum at:           17          35
 bad sum at:           18          37
 bad sum at:           36          38
 bad sum at:            6          42
 bad sum at:           21          37
 bad sum at:           43          29
 bad sum at:           19          32
 bad sum at:           41          31
 bad sum at:           20          32
 bad sum at:           45           4
 bad sum at:           44          28
 bad sum at:            6          36
 bad sum at:           60          18
 bad sum at:           22           2
 bad sum at:           52          31
 bad sum at:           19          41
 bad sum at:           40          39
 bad sum at:           20          41
 bad sum at:           41          39
 bad sum at:           24           2
 bad sum at:           21          33
 bad sum at:           23          41
 bad sum at:           32          45
 bad sum at:           47           4
 bad sum at:           53          38
 bad sum at:            8          42
 bad sum at:           51           4
 bad sum at:           43          21
 bad sum at:           18          35
 bad sum at:           61           2
 bad sum at:           62          32
 bad sum at:           12          42
 bad sum at:           57          38
 bad sum at:           14          42
 bad sum at:           15          30
 bad sum at:           72           7
 bad sum at:           34          44
 bad sum at:           17          42
 bad sum at:           58          38
 bad sum at:           63          45
 bad sum at:           37          33
 bad sum at:           18          42
 bad sum at:           38          44
 bad sum at:           65          45
 bad sum at:           28          41
 bad sum at:           43          39
 bad sum at:           29          41
 bad sum at:           20          42
 bad sum at:           53          33
 bad sum at:           52           4
 bad sum at:           23          19
 bad sum at:           22          42
 bad sum at:           41          44
 bad sum at:           52          41
 bad sum at:           56          39
 bad sum at:           45          44
 bad sum at:           29          42
 bad sum at:           57          39
 bad sum at:           21          35
 bad sum at:           58          39
 bad sum at:           48          44
 bad sum at:           54           4
 bad sum at:           59          39
 bad sum at:           57          44
 bad sum at:           38          35
 bad sum at:           63          44
 bad sum at:           68           2
 bad sum at:           17          30
 bad sum at:           70          44
 bad sum at:           12          36
 bad sum at:           11           9
 bad sum at:           28          37
 bad sum at:           16          36
 bad sum at:           70          43
 bad sum at:           68          35
 bad sum at:           11           3
 bad sum at:           70          35
 bad sum at:           72          43
 bad sum at:           72          35
 bad sum at:           38          30
 bad sum at:           67          45
 bad sum at:           27          19
 bad sum at:           15          40
 bad sum at:           22  [...]

2024-03-21 21:30 UTC, cdholmes commented
I haven't seen this error before. I can investigate tomorrow.

2024-03-22 00:46 UTC, cdholmes commented
The solution is in new PR #2211.

I was also doing 1-hour integration tests, so didn't detect this sooner. After this fix, I confirmed that the simulation runs without errors for at least 10 hours.