Run directory updates related to GEOS-IT
geoschem/geos-chem pull request #2153
Opened 2024-02-14 22:10 UTC by lizziel

### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Describe the update

To be filled in...

### Expected changes

This is a zero diff update

### Related Github Issue(s)

closes https://github.com/geoschem/GCHP/issues/379

2024-02-15 14:53 UTC, yantosca requested changes
@lizziel: Just needs a changelog entry and then it's good to merge.  Thanks for this!

2024-02-15 14:53 UTC, yantosca commented on run/shared/settings/geosit/geosit.native_ll.txt
> +EFLUX     W_m-2      N Y F0;003000 none  none EFLUX    ./MetDir/%y4/%m2/%d2/GEOS.it.asm.flx_tavg_1hr_glo_L576x361_slv.GEOS5294.%y4-%m2-%d2T%h2%n2.V01.nc4 1995-01-01T00:30:00P01:00
Q: Is the 1995-01-01T00:30:00P01:00 the reference time?

2024-02-15 18:39 UTC, yantosca approved these changes
@lizziel: I pushed the changelog update.  Now moving to integration tests

2024-02-15 18:52 UTC, lizziel commented
Oops, forgot the changelog again! I'm going to push an update on top of yours for the changelog.

2024-02-15 18:55 UTC, lizziel commented
Looks like I already did a changelog but just forgot to push. I will fix the branch.

2024-02-15 19:05 UTC, lizziel commented
All set now. I had rebased on dev/no-diff-to-benchmark but forgot to push that too. This PR now has my changelog updates and no conflicts with dev/no-diff-to-benchmark.

2024-02-16 16:27 UTC, yantosca approved these changes
I've pushed a change to make sure that `RUNDIR_OFFLINE_EMIS_RES` and `RUNDIR_OFFLINE_EMIS_LAT_RES` are defined for MERRA-2 meteorology.  Also the GCHP and GCClassic `HEMCO_Config.rc.fullchem` template files needed to be updated to replace `RUNDIR_MET_NATIVE_RES` with `RUNDIR_OFFLINE_EMIS_RES` and `RUNDIR_MET_LAT_RES` with `RUNDIR_OFFLINE_EMIS_LAT_RES`.

2024-02-16 19:42 UTC, merged

2024-02-16 21:43 UTC, yantosca commented
All GCClassic and GCHP integration tests passed. 

All GCHP integration tests were zero-diff w/r/t 14.3.0.  All GCClassic integration tests were zero-diff w/r/t 14.3.0, except:
- APM (known parallelization issue)
- RRTMG (numerical noise in RRTMG diagnostic collection output)