Remove remaining binary punch diagnostics code
geoschem/geos-chem pull request #2166
Opened 2024-02-26 21:04 UTC by yantosca

### Name and Institution (Required)

Name:
Institution:

### Confirm you have reviewed the following documentation

- [ ] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)

### Describe the update

This PR is the companion to #82. 

We have removed the following binary punch diagnostics files:

- GeosCore/diag3.F90
- GeosCore/diag_mod.F90
- GeosCore/gamap_mod.F90
- GeosCore/initialize.F90
- GeosCore/ndxx_setup.F90
- GeosUtil/bpch2_mod.F90
- Headers/CMN_DIAG_mod.F90
- Headers/CMN_O3_mod.F90

We have removed references to the above files from the following CMakeLists:

- Headers/CMakeLists.txt
- GeosCore/CMakeLists.txt
- GeosUtil/CMakeLists.txt

We have removed code contained inside `#ifdef BPCH_DIAG` blocks in these modules:

- GeosCore/aero_drydep.F90
- GeosCore/carbon_mod.F90
- GeosCore/chemistry_mod.F90
- GeosCore/dust_mod.F90
- GeosCore/flexgrid_read_mod.F90
- GeosCore/gc_environment_mod.F90
- GeosCore/hcoi_gc_diagn_mod.F90
- GeosCore/input_mod.F90
- GeosCore/ocean_mercury_mod.F90
- GeosCore/planeflight_mod.F90
- GeosCore/sulfate_mod.F90
- GeosCore/tomas_mod.F90
- GeosUtil/time_mod.F90
- Headers/input_opt_mod.F90
- Interfaces/GCClassic/main.F90

And we have removed references to bpch diagnostics in the following configuration file templates:

- run/GCClassic/geoschem.config.yml.templates/geoschem_config.yml 
- run/WRF/ch4/geoschem_config.yml
- run/WRF/fullchem/geoschem_config.yml
- Removed the "legacy_bpch" YAML section and subsections

as well as in the test/shared/commonFunctionsForTests.sh integration test script.

### Expected changes

This is a zero-diff update.  However, we should merge this into the dev/14.4.0 branch as it touches run directory configuration files.

### Related Github Issue(s)

- Closes #82

2024-02-27 18:40 UTC, msulprizio requested changes

2024-02-27 18:40 UTC, msulprizio commented on GeosCore/cleanup.F90
> -
I believe this was inadvertently removed? Please restore if so.

2024-02-27 18:40 UTC, msulprizio commented on GeosCore/hcoi_gc_diagn_mod.F90
> +       ! Create diagnostic container<
Remove extraneous "<" at end of line

2024-02-27 19:57 UTC, msulprizio approved these changes
Both minor requested changes have been addressed in https://github.com/geoschem/geos-chem/pull/2166/commits/96b4c7d65fa61adee50d392c53c3604636f99126. Good to merge.

2024-02-28 19:28 UTC, yantosca commented
This PR has been merged (locally) atop PR #1998, and integration tests are running.

2024-02-28 21:31 UTC, yantosca commented
All GEOS-Chem Classic integration tests passed:
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #d51e872 Remove BPCH_DIAG compilation option and related documentation
GEOS-Chem #7ab17802a Merge PR #2166 (Remove remaining binary punch diagnostics code)
HEMCO     #f807e1a Update HEMCO version number to 3.8.0 in preparation for release

Using 24 OpenMP threads
Number of execution tests: 26

Submitted as SLURM job: 21856850
==============================================================================


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

2024-02-29 14:57 UTC, yantosca commented
All GCHP integration tests also passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #3dbf81e GEOS-Chem submod update: Merge PR #1998 (Rename YAML tags)
GEOS-Chem #b0bc778d7 PR #2166 post-merge fix: Remove #ifdef block in read_input_file
HEMCO     #f807e1a Update HEMCO version number to 3.8.0 in preparation for release

Number of execution tests: 6

Submitted as SLURM job: 21863342
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

2024-02-29 14:58 UTC, merged