Correct the issue that injection height has been artifically decreased by HEMCO
geoschem/geos-chem pull request #2358
Opened 2024-07-01 20:54 UTC by jinlx

### Name and Institution (Required)
Name: Lixu Jin
Institution: University of Montana

### Describe the update
This update reads injection heights to account for grid-dependent issues in GFAS, as detailed in Jin et al. (2023).

This update also requires that users create the corrected injection height data first, using the code in #2330. A better approach would be to have the data created and placed in the GEOS-Chem data portals for community use.

### Expected changes
Correct the issue that injection height has been artifically decreased by HEMCO.

The independent injection height could be further used for other fire inventories.

### Reference(s)
Jin, Lixu, et al. "Constraining emissions of volatile organic compounds from western US wildfires with WE-CAN and FIREX-AQ airborne observations." Atmospheric Chemistry and Physics 23.10 (2023): 5969-5991.

### Related Github Issue
#2330

2024-07-16 18:39 UTC, yantosca commented
@jinlx: Do you have the injection height files already made?  Which resolutions do you need for this PR?

2024-08-14 19:44 UTC, jinlx commented
@yantosca Apologies for my delayed response—I was traveling last month and wasn’t able to monitor my personal emails effectively. For the inj files, I did not use 0.1x0.1 because HEMCO regrids these as emissions, which could potentially reduce the values artificially. Instead, I generated emission-corrected inj at a nested resolution (25km) for my personal use. I can extend this adjustment to other GEOS-Chem resolutions, such as 0.5x0.65, 2x2.5, and 4x5. This modification would only require a simple edit in the HEMCO_Config.rc.

Change 
```
300 GFAS_EMITL        $ROOT/GFAS/v2018-09/$YYYY/GFAS_$YYYY$MM.nc mami            2003-2023/1-12/1-31/0 C xy m 1
```
into
```
300 GFAS_EMITL_weight $ROOT/GFAS/v2024-04/$YYYY/GFAS_$YYYY$MM_hgts_$RES.nc mami_avg_weight 2003-2023/1-12/1-31/0 C xy m 1
```

2024-08-14 20:01 UTC, yantosca commented
Thanks @jinlx.  I was wondering which file to use with this PR.  It would be good if we could use the highest resolution file for all cases, if that is possible, as that is the HEMCO philosophy.

2024-09-25 15:06 UTC, yantosca commented
@jinlx: Just checking in on this PR again.  We were unsure which resolution file(s) to use with this PR.  Can you provide us with the proper file?

2024-11-20 20:15 UTC, yantosca commented
NOTE: This PR affects the GFAS biomass burning which is not enabled in fullchem benchmarks.  So we can label this as "no-diff-to-benchmark".

2024-12-05 14:48 UTC, lizziel commented
@jinlx, will be you be able to work on this? We would like to bring this into the model but are waiting for a response (see earlier post from @yantosca).

2024-12-05 15:38 UTC, jinlx commented
I was bad at monitoring github in the past months. Back to questions Bob asked:
```
I was wondering which file to use with this PR. It would be good if we could use the highest resolution file for all cases, if that is possible, as that is the HEMCO philosophy.
```
The approach I’ve been using involves having injection files of varying resolutions preloaded in the project storage with resolution-specific filenames. In HEMCO config, I reference a universal variable $RES, which allows flexibility without the need to manually edit configurations for each resolution.

I agree that it will be better to use the highest resolution files. But I am not sure if HEMCO will artificially decrease the inj value again when regriding from high to resolutions. May need a little efforts from people understand both injection and hemco well (?).

```
Can you provide us with the proper file?
```
I will provide corrected inj files in standard resolutions, i.g., 2x2.5, 4x5, 0.25x0.3125, and 0.5x0.625 here after AGU, so that people can use it whether if it is implemetned in the future versions.

Again, sorry for not staying on notifications well. I will set up notifications for my school email moving forward so I can respond more promptly.

2025-06-23 20:36 UTC, yantosca commented
@jinlx do you have the files for this PR?

2025-07-09 02:20 UTC, jinlx commented
Thanks for the nudge @lizziel and @yantosca ! I have extended the files I used to support multiple horizontal resolutions for the years 2018 and 2019. These can now be used for benchmarking purposes. You can find them under:
```
.../ExtData/HEMCO/GFAS/v2025-07
```

[forGCST.zip](https://github.com/user-attachments/files/21133484/forGCST.zip)

Users can easily generate customized years using the reproducible Python workflow by simply modifying the directory path and year in the script. Please see ``GFAS_injs.py`` and ``README.md`` included in the archive for more details.

To enable GEOS-Chem to dynamically select resolution-specific files, please update the ``HEMCO_Config.rc`` as follows:

**Old line:**
Again, to make the GEOS-Chem dynamically select the right resolution. We need to make corresponding changes in the HEMCO_Config.rc.
```
300 GFAS_EMITL        $ROOT/GFAS/v2018-09/$YYYY/GFAS_$YYYY$MM.nc mami            2003-2023/1-12/1-31/0 C xy m 1
```
**New line:**
```
300 GFAS_EMITL_weight $ROOT/GFAS/v2025-07/$YYYY/GFAS_$YYYY$MM_hgts_$RES.nc mami_avg_weight 2003-2023/1-12/1-31/0 C xy m 1
```
Let me know if you have any questions.

Best,
Lixu

2025-07-09 16:44 UTC, jinlx commented
Hi @lizziel and @yantosca,

Thanks for the nudge and for your patience! I extended the GFAS files to support multiple horizontal resolutions for 2018 and 2019, which should be easy to use for benchmarking. You can find them under:
```
.../ExtData/HEMCO/GFAS/v2025-07
```
I also modularized my old python code so users can easily customize the year and resolution (provided they have ``/HEMCO/GFAS`` downloaded). Please see ``GFAS_injs.py`` and ``README.md`` included in the archive for more details.

To enable GEOS-Chem to dynamically select resolution-specific files, please update the ``HEMCO_Config.rc`` as follows:

To make the GEOS-Chem dynamically select the right resolution. We need to make corresponding changes in the HEMCO_Config.rc.

**Old line:**
```
300 GFAS_EMITL        $ROOT/GFAS/v2018-09/$YYYY/GFAS_$YYYY$MM.nc mami            2003-2023/1-12/1-31/0 C xy m 1
```
**New line:**
```
300 GFAS_EMITL_weight $ROOT/GFAS/v2025-07/$YYYY/GFAS_$YYYY$MM_hgts_$RES.nc mami_avg_weight 2003-2023/1-12/1-31/0 C xy m 1
```

**The archived data and code:** [Inj4GCST.zip](https://github.com/user-attachments/files/21146852/Inj4GCST.zip)

Let me know if you have any questions.

Best,
Lixu

2025-07-09 18:16 UTC, yantosca commented
Thanks @jinlx!  I'll take a look at this shortly.

2025-07-10 17:01 UTC, yantosca requested changes
Thanks @jinlx, this looks good.  I just have a couple of updates:

1. Can you add the corresponding change for scale factor 300 to the `run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem` file?
2. We would also need a quick sentence describing the update in the `CHANGELOG.md` file.  This could go under the `### Added` section

2025-07-10 18:33 UTC, jinlx commented
Hi @yantosca,

The updates in ``HEMCO_Config.rc.templates``  apply equally to both GCHP and Classic. So, we’ll need to make the corresponding changes in:
- ``run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem`` 
- ``run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem``

**Old line:**
```
300 GFAS_EMITL        $ROOT/GFAS/v2018-09/$YYYY/GFAS_$YYYY$MM.nc mami            2003-2023/1-12/1-31/0 C xy m 1
```
**New line:**
```
300 GFAS_EMITL_weight $ROOT/GFAS/v2025-07/$YYYY/GFAS_$YYYY$MM_hgts_$RES.nc mami_avg_weight 2003-2023/1-12/1-31/0 C xy m 1
```

For ``CHANGELOG.md``, how about:

```
- Added support for resolution-specific GFAS injection height files in HEMCO_Config.rc
```
Let me know if that works!

Best,
Lixu

2026-01-22 22:56 UTC, msulprizio commented
@jinlx Do you know if/how this update differs from the implementation in [Singh et al. 2025](https://pubs.acs.org/doi/10.1021/acsestair.5c00035)?

Also tagging @inder-math and @yuanjianz for comment.

2026-01-23 17:05 UTC, yuanjianz commented
@msulprizio Yes, Jin et al. 2023 and Singh et al. 2025 are different implementations. In the current HEMCO folders, Singh et al. 2025 is v2025-05 and Jin et al. 2023 is v2025-07.

2026-08-25 13:49 UTC, yantosca commented
Similar functionality has been implemented via https://github.com/geoschem/geos-chem/pull/3317 and https://github.com/geoschem/HEMCO/pull/362.  Closing this PR.

2026-08-25 13:49 UTC, closed without merging