Changes for coupling GEOS-Chem to CESM in Spectral-element Dynamical Core (CAM-SE)
geoschem/geos-chem pull request #2366
Opened 2024-07-09 01:33 UTC by jimmielin

### Name and Institution (Required)

Name: Haipeng Lin
Institution: Harvard Univ.

### Describe the update

These updates are structural and affect GEOS-Chem within CESM model only. They are intended to allow the GEOS-Chem chemistry to work using the spectral element dynamical core in the Community Atmosphere Model, the atmospheric component in CESM.

### Expected changes

Zero-diff.

### Reference(s)

N/A

### Related Github Issue

Fixes issues:
* https://github.com/geoschem/CAM/issues/36

2024-07-09 14:01 UTC, lizziel requested changes

2024-07-09 14:01 UTC, lizziel commented on Headers/state_grid_mod.F90
> +#if defined( MODEL_WRF ) || defined( MODEL_CESM )
Could you add a clarifying comment in this block with more about what these are? Does each CPU have a different ID while root ID is the same for all? Or does each domain have a fixed ID and is handled by multiple CPUs such that multiple CPUs have the same ID?

2024-07-09 15:02 UTC, jimmielin commented
Thank you, changelog updated and the trailing slash change reverted.

2024-07-10 15:55 UTC, lizziel approved these changes
Looks good to merge.

2024-07-10 17:57 UTC, merged