KPP Standalone from Obin Sturm
geoschem/geos-chem pull request #2483
Opened 2024-09-26 19:45 UTC by lizziel

### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Describe the update

This draft PR contains updates for KPP Standalone from Obin Sturm (GMAO) contained in https://github.com/GEOS-ESM/geos-chem/pull/19. That original PR is built off of branch geos/develop in the GEOS-Chem fork in GMAO's GitHub. That version is not mergable into the standard model so this PR will be used instead.

Tagging @obin1, @yantosca

### Expected changes

See https://github.com/GEOS-ESM/geos-chem/pull/19

### Reference(s)

https://github.com/KineticPreProcessor/KPP-Standalone/tree/kpp-standalone

### Related Github Issue

https://github.com/GEOS-ESM/geos-chem/pull/19
Please link to the corresponding Github issue(s) here. If fixing a bug, there should be an issue describing it with steps to reproduce.

2024-09-27 13:55 UTC, yantosca requested changes
Thanks @lizziel for prepping this PR.  I have some changes:

1. Remove the `.exe` file from the repo, we shouldn't track binaries.
2. I would prefer to see all of the standalone files go into a `KPP/standalone` folder.  This would make it easier to also create standalone simulations for the other mechanisms if so desired.

2024-09-27 14:01 UTC, yantosca reviewed
Also I think we can make a folder `KPP/standalone/sample_input` (or something named accordingly) to place the sample input files in.  It'd be nice to eventually have one for each mechanism.

2024-10-03 17:54 UTC, yantosca commented
@obin1 @lizziel: NOTE: I removed the binary file kpp_executable.exe and pushed to this PR branch.  I will make further updates to this PR and let you know when it is ready for review.  Thanks!

2024-10-10 14:25 UTC, obin1 commented on KPP/standalone/kpp_standalone_init.F90
@yantosca I'm wondering about the new HEMCO dependencies -- do you think there's any way we could use the built-in command_argument_count and get_command_argument instead? I worry that making this dependent on HEMCO means that I (and other users) won't be able to use this as a true standalone, outside of the GEOS-Chem environment. 

Could we do instead try an approach like the beginning of kpp_standalone.F90 to handle arguments and kwargs? What do you think?

2024-10-10 15:41 UTC, yantosca commented on KPP/standalone/kpp_standalone_init.F90
Hi @obin1, yes we will not use HEMCO dependencies.  I will investigate how to make kpp_standalone handle args and kwargs, I have experience doing this before.  Will work in the forked KPP-Standalone repo for now.

2024-11-21 20:17 UTC, yantosca commented
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

CodeDir   : b4cea44 GEOS-Chem update: Merge PR #2482 (KPP standalone interface)
GEOS-Chem : 860b90cdd Merge PR #2483 (KPP standalone from Obin Sturm)
HEMCO     : deaa192 HEMCO 3.10.0 release
Cloud-J   : f8a2b7f Update version number for 8.0.1 release
HETP      : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Using 24 OpenMP threads
Number of execution tests: 30

Submitted as SLURM job: 59046109
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

2024-11-21 20:41 UTC, yantosca approved these changes

2024-11-21 20:43 UTC, yantosca commented
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

CodeDir       : a7ab3eb GEOS-Chem update: Merge PR #2482 (KPP standalone interface)
MAPL          : 9ad63ae Merge PR #37 containing update to vertically flip imports with dimensionless pressure proxy lev coordinates
GMAO_Shared   : 4ddb3ec Merge pull request #2 from geoschem/feature/mapl-upgrade
ESMA_cmake    : ad5deba Added ecbuild as a submodule of ESMA_cmake
gFTL-shared   : 4b82492 Merge branch 'upstream_v1.5.0' into feature/v1.5.0
FMS           : 259759d Merge pull request #3 from geoschem/feature/update_gmao_libs
FVdycoreCubed : af42462 Merge PR #8 (Add PLEadv diagnostic for offline advection in GCHP)
geos-chem     : 860b90cdd Merge PR #2483 (KPP standalone from Obin Sturm)
HEMCO         : deaa192 HEMCO 3.10.0 release
yaFyaml       : 19afe50 Merge branch 'upstream_v1.0.4' into feature/v1.0.4
pFlogger      : 2c4b724 Merge branch 'upstream_v1.9.1' into feature/v1.9.1
Cloud-J       : f8a2b7f Update version number for 8.0.1 release
HETP          : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Number of execution tests: 12

Submitted as SLURM job: 59046957
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

2024-11-21 20:57 UTC, obin1 approved these changes
All looks good, approving so @yantosca can merge

2024-11-21 21:02 UTC, yantosca approved these changes

2024-11-21 21:06 UTC, obin1 approved these changes

2024-11-21 21:16 UTC, merged