Fix CEDS TMB emissions
geoschem/geos-chem pull request #2507
Opened 2024-10-09 19:54 UTC by kelvinhb

### Name and Institution (Required)

Name: Kelvin Bates
Institution: CU Boulder

### Describe the update

Changed the CEDS TMB emission fields to actually emit TMB like they're supposed to, instead of emitting HCOOH. I'm not sure if this fix needs to go into any other HEMCO_Config.rc template files, either in run/GCClassic or in other run/ directories, but hopefully we can make any other necessary changes down the line. Currently the only change is to HEMCO_Config.rc.fullchem.

### Expected changes

Emissions of HCOOH will decrease (specifically anthropogenic emissions from the CEDS inventory), and those of TMB will increase. This should have minimal knock-on effects to oxidants.

### Reference(s)

N/A

### Related Github Issue

N/A

2024-10-10 21:08 UTC, yantosca requested changes
Thanks for the PR @kelvinhb, it looks good.  A couple of things:

1. We'd also need to make the same change in `run/GCHP/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem`
2. Would you be able to update the CHANGELOG.md file?   You can add a one-liner note under Unreleased -> Fixed saying "Fixed CEDS HEMCO_Config.rc entries to emit TMB into the TMB species (and not HCOOH)".  We now require CHANGELOG.md updates for each PR.

Thanks!

2024-10-11 21:49 UTC, kelvinhb commented
Hi @yantosca -- I think I've made these changes as needed, let me know if there's anything else that needs doing!

2024-11-19 21:10 UTC, yantosca approved these changes
Thanks @kelvinhb!  These changes look good to merge.

2024-11-19 21:26 UTC, yantosca commented
@kelvinhb: Is it OK if I push merge conflict resolutions back to your [kelvinhb:Fix-CEDS-TMB-emissions](https://github.com/kelvinhb/geos-chem/tree/Fix-CEDS-TMB-emissions) branch?  This will make the updates show up on the PR.  It will also bring in updates from the 14.5.0 release, so if you don't want that, let me know.

2024-11-19 21:47 UTC, kelvinhb commented
I think that should be fine... does it need any action on my end?

2024-11-19 22:04 UTC, yantosca commented
@kelvinhb: No action on your end needed.  As long as you are not actively using the branch that'll be OK.

2024-11-20 15:13 UTC, yantosca commented
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

CodeDir   : cc01a47 GCClassic 14.5.0 release
GEOS-Chem : a1b784fd7 PR #2507 post-merge fixes: Update CHANGELOG.md
HEMCO     : deaa192 HEMCO 3.10.0 release
Cloud-J   : f8a2b7f Update version number for 8.0.1 release
HETP      : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Using 24 OpenMP threads
Number of execution tests: 30

Submitted as SLURM job: 58707404
==============================================================================
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

All GCHP execution tests also passed:
```console
==============================================================================
GCHP: Execution Test Results

CodeDir       : a9e7c3f GCHP 14.5.0 release
MAPL          : 9ad63ae Merge PR #37 containing update to vertically flip imports with dimensionless pressure proxy lev coordinates
GMAO_Shared   : 4ddb3ec Merge pull request #2 from geoschem/feature/mapl-upgrade
ESMA_cmake    : ad5deba Added ecbuild as a submodule of ESMA_cmake
gFTL-shared   : 4b82492 Merge branch 'upstream_v1.5.0' into feature/v1.5.0
FMS           : 259759d Merge pull request #3 from geoschem/feature/update_gmao_libs
FVdycoreCubed : af42462 Merge PR #8 (Add PLEadv diagnostic for offline advection in GCHP)
geos-chem     : a1b784fd7 PR #2507 post-merge fixes: Update CHANGELOG.md
HEMCO         : deaa192 HEMCO 3.10.0 release
yaFyaml       : 19afe50 Merge branch 'upstream_v1.0.4' into feature/v1.0.4
pFlogger      : 2c4b724 Merge branch 'upstream_v1.9.1' into feature/v1.9.1
Cloud-J       : f8a2b7f Update version number for 8.0.1 release
HETP          : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Number of execution tests: 12

Submitted as SLURM job: 58708357
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

2024-11-20 19:03 UTC, merged