Bug fix: allow uppercase log filename in download_data.py
geoschem/geos-chem pull request #2508
Opened 2024-10-10 09:49 UTC by ihough

### Name and Institution (Required)

Name: Ian Hough
Institution: Université Grenoble Alpes

### Describe the update

Fixes a bug where `download_data.py` fails if the dryrun log filename contains uppercase characters e.g. 'Log.dryrun'. The solution is to not coerce the dryrun log filename to lowercase.

### Expected changes

No changes to model output

### Reference(s)

None

### Related Github Issue

[#70](https://github.com/geoschem/GCClassic/issues/70)

2024-10-10 14:05 UTC, yantosca requested changes
Thanks for this @ihough.  It looks good to merge.  But would you also be able to add a note in the CHANGELOG.md under the Unreleased / Changed section?  We require the changelog update for all PRs.  Thanks!

2024-10-14 08:01 UTC, ihough commented
@yantosca updated the changelog.

2024-11-19 20:21 UTC, yantosca commented
@ihough: Is it OK if I push back to this branch on your fork? That way the updates will show up on the PR.

2024-11-19 21:20 UTC, ihough commented
@yantosca sure push away!

2024-11-19 22:00 UTC, yantosca commented
Thanks @ihough

2024-11-20 20:14 UTC, yantosca commented
NOTE: I pushed updates before changing the base branch.  This PR will close when merged into main.

2025-01-10 17:50 UTC, merged