Fixes towards achieving bit-for-bit reproducibility in GC-Classic upon restart
geoschem/geos-chem pull request #2521
Opened 2024-10-15 19:36 UTC by lizziel

### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Describe the update

This PR applies changes in GC-Classic needed to achieve bit-for-bit reproducibility when breaking up a run in time. With these updates GC-Classic still does not have reproducibility upon restart due to the following issues:
1. HEMCO reads inputs, including GEOS-Chem restart file variables, as single precision when most of these fields in GEOS-Chem are double precision.
2. There is a parallelization issue in GEOS-Chem's computation of `State_Chm%DryDepNitrogen` (and possibly `State_Chm%WetDepNitrogen`) used in the HEMCO soil NOx extension. I believe this was previously undetected because the differences are at the level of double precision numerical noise and thus were previously obscured by outputting to file as single precision. This update includes writing to the restart file using native precision which exposed the issue.

More details on this PR coming soon.

### Expected changes

This update will cause small differences in all GEOS-Chem Classic simulations.

### Reference(s)

None

### Related Github Issue

https://github.com/geoschem/geos-chem/issues/2014
Possibly others. Will put them here once found.

2024-10-15 20:14 UTC, yantosca commented
@lizziel, I think I know what this may be.  The N deposition code (I think `GET_N_DEP`) is trying to sum data into a 2-D array within a 3-D parallel loop.  This might lead to numerical differences if the loop over levels (L) is parallelized.   

You could get around that by declaring the variable to hold the level sum with `!$OMP REDUCTION(+: varname)`.   But it might just be more elegant to store the N deposition in a 3-D field of State_Met which could be summed in the vertical outside of a parallel loop.  I think the N deposition code pre-dated the State objects in GC v11-01.

2025-02-18 17:59 UTC, yantosca requested changes
Thanks @lizziel, this looks mostly good.  I just had a few minor comments.

2025-02-18 17:59 UTC, yantosca commented on GeosCore/hco_interface_gc_mod.F90
> +             !$OMP PRIVATE( I, J, tmpFlx )
Add a `!$OMP COLLAPSE( 2 )` statement here, which will vectorize the loop.

2025-02-18 17:59 UTC, yantosca commented on GeosCore/hco_utilities_gc_mod.F90
> +            WRITE( 6, 530 ) N, TRIM( SpcInfo%Name ), &
I think we can simply replace `SUM ( Ptr3D(:,:,1:State_Grid%NZ) )` with `SUM( Ptr3D )` since the `Temp3D` array is defined with NZ levels.

2025-02-18 17:59 UTC, yantosca commented on GeosCore/hco_utilities_gc_mod.F90
> +            Spc(N)%Conc(I,J,L) = Ptr3D(I,J,L)
Can add a `!$OMP COLLAPSE( 3 )` statement to vectorize this loop.

2025-02-18 17:59 UTC, yantosca commented on GeosCore/hco_utilities_gc_mod.F90
>     ! Get variables for KPP mechanisms (right now just fullchem and Hg)
The comment should read `(right now fullchem, Hg, and carbon)'

2025-02-18 17:59 UTC, yantosca commented on Interfaces/GCClassic/main.F90
> +
@lizziel: Should we also start the unit conversion timer here?

2025-02-18 17:59 UTC, yantosca commented on Interfaces/GCClassic/main.F90
> +
@lizziel: Should we end the unit conversion timer here?

2025-02-18 17:59 UTC, yantosca commented on Interfaces/GCClassic/main.F90
> +       !---------------------------------------------------------------------
Should we start the unit conversion timer here?

2025-02-18 17:59 UTC, yantosca commented on Interfaces/GCClassic/main.F90
> +
Should we end the unit conversion timer here?

2025-02-18 19:05 UTC, lizziel commented on Interfaces/GCClassic/main.F90
> +
I don't think so since the unit conversion timer start and end are within Convert_Spc_Units.

2025-02-18 19:07 UTC, lizziel commented on GeosCore/hco_utilities_gc_mod.F90
>     ! Get variables for KPP mechanisms (right now just fullchem and Hg)
This is unrelated to the PR changes. Could that update go into docs/dev?

2025-02-18 19:15 UTC, lizziel commented on GeosCore/hco_utilities_gc_mod.F90
>     ! Get variables for KPP mechanisms (right now just fullchem and Hg)
Actually, looking at this code, are you sure it is supposed to include carbon? The section is to retrieve `KPP_HVALUE` from the restart file. If it should include carbon then there is a bug that would need to be fixed.

2025-02-18 19:18 UTC, lizziel commented on GeosCore/hco_utilities_gc_mod.F90
> +            WRITE( 6, 530 ) N, TRIM( SpcInfo%Name ), &
Done!

2025-02-18 19:18 UTC, lizziel commented on GeosCore/hco_utilities_gc_mod.F90
> +            Spc(N)%Conc(I,J,L) = Ptr3D(I,J,L)
Done!

2025-02-18 19:39 UTC, yantosca approved these changes
Thanks @lizziel.  This is good to merge now.

2025-02-20 18:51 UTC, yantosca commented
After merging locally atop 14.6.0-alpha.8, all GCClassic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

CodeDir   : 797f2ca GEOS-Chem update: Merge PR #2523 (Fix PDOWN def & reevap req)
GEOS-Chem : b1676fe42 Merge PR #2521 (Bit-for-bit reproducibility in GCClassic)
HEMCO     : 2423647 Merge PR #279 (Use USTAR from met in DustDEAD extension)
Cloud-J   : f8a2b7f Update version number for 8.0.1 release
HETP      : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Using 24 OpenMP threads
Number of execution tests: 30

Submitted as SLURM job: 4282271
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
as well as all GCHP integration tests:
```console
==============================================================================
GCHP: Execution Test Results

CodeDir       : 5da2a88 GEOS-Chem update: Merge PR #2523 (Fix PDOWN def & reevap req)
MAPL          : 6207fd0 Merge pull request #38 from geoschem/bugfix/intel_build_error_in_AbstractComponent
GMAO_Shared   : 4ddb3ec Merge pull request #2 from geoschem/feature/mapl-upgrade
ESMA_cmake    : ad5deba Added ecbuild as a submodule of ESMA_cmake
gFTL-shared   : 4b82492 Merge branch 'upstream_v1.5.0' into feature/v1.5.0
FMS           : 259759d Merge pull request #3 from geoschem/feature/update_gmao_libs
FVdycoreCubed : af42462 Merge PR #8 (Add PLEadv diagnostic for offline advection in GCHP)
geos-chem     : b1676fe42 Merge PR #2521 (Bit-for-bit reproducibility in GCClassic)
HEMCO         : 2423647 Merge PR #279 (Use USTAR from met in DustDEAD extension)
yaFyaml       : 19afe50 Merge branch 'upstream_v1.0.4' into feature/v1.0.4
pFlogger      : 2c4b724 Merge branch 'upstream_v1.9.1' into feature/v1.9.1
Cloud-J       : f8a2b7f Update version number for 8.0.1 release
HETP          : 2a99b24 Merge pull request #2 from geoschem/bugfix/initialize_local_variables

Number of execution tests: 12

Submitted as SLURM job: 4282450
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

2025-02-20 18:51 UTC, merged