Extending Stratospheric Adjustment to GCClassic
geoschem/geos-chem pull request #2525
Opened 2024-10-17 11:23 UTC by cbarker211

### Name and Institution

Name: Connor Barker, @eamarais
Institution: University College London (UCL)

### Describe the update

This update extends the stratospheric adjustment code added by @sdeastham in GCHP (https://github.com/geoschem/geos-chem/pull/2010) to GCClassic. The commit here simply modifies the main level script for GCClassic, and allows the dynamical heating rates to be read in via the HEMCO meteorology file. No changes are made to the underlying RRTMG source code beyond what Seb already has added to include stratospheric adjustment. For further details see the original pull request.

To include stratospheric adjustments of temperature relative to the baseline simulation in the radiative fluxes, follow these steps:

    - Run a baseline simulation with no pertubations.
        - Set the following in geoschem_config.yml (rrmtg must be activated): 
            - fixed_dyn_heating: true
            - read_dyn_heating: false
        - Activate the DynHeating collection in HISTORY.rc (sample file provided below) - this outputs the dynamical heating rates.

    - Run a pertubation simulation.
        - Create a symbolic link in the run directory called Heating_Baseline to point to the DynHeating output from the baseline simulation:
            - e.g. ln -s /path/to/reference/rundir/OutputDir Heating_Baseline
        - Set the following in geoschem_config.yml (rrmtg must be activated): 
            - fixed_dyn_heating: true
            - read_dyn_heating: true
        - Add the following to the HEMCO_Config.rc.gmao_metfields file - this loads the dynamical heating rates:
            - # --- DynHeating field ---
            - * DynHeating  ./Heating_Baseline/GEOSChem.DynHeating.$YYYY$MM$DD_$HH00z.nc4 DynHeating 2019/1-12/1-31/0-23 I xyz 1 * - 1 1
[HISTORY.txt](https://github.com/user-attachments/files/17411390/HISTORY.txt)

As described in https://github.com/geoschem/geos-chem/pull/2010, occasionally there will be a warning of "RRTMG FDH routine failed to converge for x of y columns on CPU 0". We find this happens sporadically for our simulations for 1/3312 columns. Failing to converge for >10 columns usually indicates an error somewhere.

The seasonally-evolving fixed dynamical heating approximation has also been extended to GCClassic, but is not yet tested (as stated by Seb in https://github.com/geoschem/geos-chem/pull/2010). The fdh_to_toa flag can be added in geoschem_config.yml to extend the stratospheric adjustment calculations to the top of the model.

### Expected changes

This code can be tested by simulating a single day with and without an increase of 100 ppmv CO2 (see https://github.com/geoschem/geos-chem/pull/2010).

    - 20190701 - 20190702, no spinup, default restart file.
    - 4 simulations:
        - baseline   (co2_ppmv: 390.0, read_dyn_heating: false)
        - without_sa (co2_ppmv: 490.0, read_dyn_heating: false)
        - sa_strat   (co2_ppmv: 490.0, read_dyn_heating: true, fdh_to_toa: false)
        - sa_toa     (co2_ppmv: 490.0, read_dyn_heating: true, fdh_to_toa: true)
    - If successful, you should get the following results.  
        -           Sim  TOA RF / W m-2  Trop CO2 RF / W m-2  TOA RF - Trop RF / W m-2
         0        No SA            0.64                 1.25                     -0.61
         1  SA in strat            1.10                 1.24                     -0.09
         2    SA to TOA            1.16                 1.24                     -0.02
        - The expected changes are an increase in the TOA RF, and a small decrease in the Trop CO2 RF. 

### References

See https://github.com/geoschem/geos-chem/pull/2010

2024-10-17 15:44 UTC, msulprizio commented
Thanks @cbarker211. I've marked this item as delivered on our [Model Development Priorities](https://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_model_development_priorities#Prioritized_and_in_the_queue) page.

2024-10-17 16:14 UTC, cbarker211 commented
Thanks, just to add this is the update "Strat-adjusted RF in GCC and GCHP", rather than "Fixes to stratospheric aerosol settling".

2025-01-17 19:56 UTC, yantosca requested changes
Thanks @cbarker211 for this update.  I had a few comments, see attached.  We'd also need a changelog update.

Also tagging @lizziel

2025-01-17 19:56 UTC, yantosca commented on GeosCore/flexgrid_read_mod.F90
> +    ! Name of this routine (for error printout)
@cbarker211 can we remove these commented-out lines if they aren't needed?

2025-01-17 19:56 UTC, yantosca commented on Interfaces/GCClassic/main.F90
> +
@cbarker211 Could this be placed into a subroutine after the `CONTAINS` statement in `main.F90` and just called from here?  That would reduce clutter in an already-long `main.F90` program.

2025-01-17 19:56 UTC, yantosca commented on Interfaces/GCClassic/main.F90
> +          IF (Allocated(DT_3D)) Deallocate(DT_3D, STAT=RC)
It would be more efficient to allocate all necessary arrays once in initialization and then to deallocate them at finalaization rather than on every timestep.

2026-02-20 20:58 UTC, yantosca commented
Thanks @cbarker211 and @eamarais.  I've rebased this code atop GEOS-Chem 14.7.0.  I will close this PR.  Further work on this will be handled in this PR:
- #3211

2026-02-20 20:58 UTC, closed without merging