Added a new inorganic nucleation subroutine to tomas_mod.F90.
geoschem/geos-chem pull request #2528
Opened 2024-10-17 20:08 UTC by samuelod-atmos

The nucleation scheme is based on this paper:
https://www.science.org/doi/10.1126/science.aaf2649.

### Name and Institution (Required)

Name: Samuel O'Donnell
Institution: Colorado State University

### Describe the update

We have added a new inorganic nucleation mechanism to the TOMAS aerosol package. The nucleation mechanisms are based on Dunne et al. (2016; https://www.science.org/doi/10.1126/science.aaf2649), and was originally written by Jeff Pierce at CSU. We have not included the organic nucleation mechanism outlined in Riccobono et al. (2014) which is part of the Dunne et al. (2016) paper.

A new switch has been added (dunn_nuc; 0/1) in order to turn the mechanism off/on, consistent with the existing inorganic nucleation mechanisms. The updated scheme uses sulfuric acid (molecules/cm^3) and ammonia (molecules/cm^3) in a simple power-law function to give the formation rate of small particles. In order to better match observations of new particle formation events at the Southern Great Plains (SGP) observatory, we had to scale up the nucleation mechanism by 1000x for the 15 bin simulation. This updated is relatively untested with TOMAS40, so the 1000x multiplier should be tested with a TOMAS40 simulation. 

### Expected changes

Overall, nucleation and particle growth is a buffered system, so the nucleation rates should result in little changes to bulk aerosol mass. Ideally, the updated mechanisms should lead to better agreement with observations in terms of new particle formation event frequency, duration, and strength throughout the globe, but we have only tested this at the SGP site so far. 

### Reference(s)

The work with updates to TOMAS are not published yet. 

### Related Github Issue

Please link to the corresponding Github issue(s) here. If fixing a bug, there should be an issue describing it with steps to reproduce.

2024-12-02 22:09 UTC, yantosca commented
Also tagging @BettyCroft who has worked with TOMAS more recently

2025-01-27 20:49 UTC, yantosca reviewed
Thanks for this PR @samuelod-atmos.  I've noted several minor issues.

Also would add a note to the CHANGELOG.md file under the `Added` section Something 
```markdown
- Added new inorganic nucleation subroutine to `tomas_mod.F90` (cf.   10.1126/science.aaf2649)
```

2025-01-27 20:51 UTC, yantosca requested changes
Thanks for this PR @samuelod-atmos.  I've noted several minor issues.

Also would add a note to the CHANGELOG.md file under the `Added` section Something 
```markdown
- Added new inorganic nucleation subroutine to `tomas_mod.F90` (cf. 10.1126/science.aaf2649)
```

2025-07-10 21:26 UTC, samuelod-atmos commented
Hi @yantosca, just curious about the next steps that I need to take to get this merged. Thanks!

2025-07-11 15:13 UTC, yantosca commented
Thanks @samuelod-atmos.  Can you resolve the issues that I've mentioned and push updates to this branch?

2025-07-15 19:21 UTC, samuelod-atmos commented
Thanks, @yantosca! I just want to make sure I'm doing this correctly. I thought I pushed most of the updates to tomas_mod.F90 to this branch, but I may be mistaken. Should I resolve the issues I've addressed here on github? Sorry, I'm still learning the details of contributing.

2025-07-15 19:39 UTC, yantosca commented
Thanks @samuelod-atmos.   If you push to the main branch in your fork then the updates will show up on the PR here and then I can review them.

2025-07-15 19:40 UTC, yantosca commented
Thanks @samuelod-atmos, maybe this slipped thru the cracks on my part.  I'll take a look.

2025-07-15 19:43 UTC, samuelod-atmos commented
Thanks, @yantosca! I definitely haven't updated everything (e.g., AIRMW), so I'll try to get to that ASAP.

2026-05-04 22:09 UTC, BettyCroft commented
Hi @yantosca, After discussion with @theloniuspunk, we can discontinue this pull request since the newer PR https://github.com/geoschem/geos-chem/pull/3257 includes these updates as well as additional developments.

2026-05-07 15:14 UTC, yantosca commented
Thanks all.  I'll close this and proceed to merge in PR #3257.

2026-05-07 15:14 UTC, closed without merging