Bugfix/carbon sim
geoschem/geos-chem pull request #2554
Opened 2024-11-04 20:04 UTC by msulprizio

### Name and Institution (Required)

Name: Melissa Sulprizio & Lizzie Lundgren
Institution: Harvard University

### Describe the update

This pull request contains several fixes and updates to the carbon simulation to (1) reproduce carbon species in the GCClassic standalone CH4, CO2, and tagCO simulations and (2) ensure consistent results between the carbon simulation in GCClassic and GCHP.

### Expected changes

These changes impact only the carbon, CH4, CO2, and tagCO simulations and do not impact the full-chemistry benchmark simulations.

### Related Github Issue

- https://github.com/geoschem/GCHP/issues/440
- https://github.com/geoschem/geos-chem/issues/2387

2024-11-12 22:57 UTC, Aosrain commented
@msulprizio I can successfully compile GCHP 14.5.0, but when I include these bug fixes, the following error appears. 

[ 93%] Building Fortran object src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/GeosCore/CMakeFiles/GeosCore.dir/emissions_mod.F90.o
/nobackup/lwu5/GCHP/src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/GeosCore/emissions_mod.F90(127): error #6580: Name in only-list does not exist or is not accessible.   [EMISS_CARBON_GASES]
    USE Carbon_Gases_Mod,      ONLY : Emiss_Carbon_Gases
--------------------------------------^
compilation aborted for /nobackup/lwu5/GCHP/src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/GeosCore/emissions_mod.F90 (code 1)
make[2]: *** [src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/GeosCore/CMakeFiles/GeosCore.dir/build.make:283: src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/GeosCore/CMakeFiles/GeosCore.dir/emissions_mod.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:11451: src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/GeosCore/CMakeFiles/GeosCore.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

2024-11-21 00:01 UTC, Aosrain commented
@yidant Would you please upload $ROOT/CH4/v2024-01/ResME/reservoir_mask.01x01.nc to the data server? Thank you.

2024-11-21 00:07 UTC, yidant commented
Thanks @Aosrain! This file is synced!

2025-01-07 20:07 UTC, msulprizio commented
1-month benchmarks for January 2019 at 4x5 resolution have been completed with GCClassic and comparisons of the CO, CO2 and, CH4 in the "offline" specialty simulations has been compared to the joint and single-species carbon simulations. 

Performance results are outlined below:

<img width="401" alt="Screenshot 2025-01-07 at 3 05 18 PM" src="https://github.com/user-attachments/assets/18925f78-52fe-4ece-b509-e63889a56c62" /><br>

Difference plots may be viewed here: [GCClassic_Carbon_comparisons.pdf.zip](https://github.com/user-attachments/files/18337888/GCClassic_Carbon_comparisons.pdf.zip) (compressed because of file size limit). These plots show: (1) CO2 is identical between the CO2 simulation and CO2 in the carbon simulation; (2) There are numerical differences in CH4 in the CH4 simulation vs the CH4-only carbon simulation due to performance of the chemistry in KPP vs in global_ch4_mod.F90; (3) Some differences still exist in CO when comparing the tagCO simulation with the CO-only carbon simulation, but perhaps the user community can help sort these out.

As such, I think this PR is now ready for merging into dev/no-diff-to-benchmark for inclusion in 14.5.1.

Tagging @lizziel and @yantosca

2025-01-07 20:36 UTC, yantosca requested changes
Thanks @msulprizio.  I just had a comment about the CHANGELOG.md

2025-01-07 20:36 UTC, yantosca commented on CHANGELOG.md
> +- Changed dimension of EmisOCS_Total from 2D to 3D since all emissions for all sectors are 2D
Should this be 3D to 2D?

2025-01-07 20:36 UTC, yantosca commented on run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.tagCO
> +    --> QFED2                  :       false    # 2000-2020
@msulprizio: TagCO uses QFED2 because the GFED extension biomass emissions cannot be masked.  But this is OK to disable QFED2 since we are deprecating the tagCO simulation.

2025-01-08 13:17 UTC, msulprizio commented on CHANGELOG.md
> +- Changed dimension of EmisOCS_Total from 2D to 3D since all emissions for all sectors are 2D
Yes, according to commit https://github.com/geoschem/geos-chem/pull/2554/commits/77d7fea5e0c340dec417f3ce26c103e0af239ba1 it should be 3D to 2D. Now fixed in https://github.com/geoschem/geos-chem/pull/2554/commits/efedff3fee4eedc69b0163cecfa77c9093f23d31.

2025-01-08 18:59 UTC, merged

2025-01-08 19:00 UTC, msulprizio commented
All GCClassic and GCHP integrations pass