Add run directory creation support for processed cubed-sphere GEOS-IT meteorology
geoschem/geos-chem pull request #2616
Opened 2024-12-06 19:23 UTC by yuanjianz

### Name and Institution (Required)

Name: Yuanjian Zhang
Institution: WashU

### Describe the update

Add run directory creation support for processed cubed-sphere GEOS-IT meteorology

2025-01-09 15:38 UTC, lizziel requested changes

2025-01-09 15:38 UTC, lizziel commented on CHANGELOG.md
> +- Added createRunDir for processed cubed-sphere GEOS-IT meteorology
Change to "Added run directory creation for processed cubed-sphere GEOS-IT meteorology". As is, it reads as if a new createRunDir was added, when the existing one was just modified.

2025-01-09 15:38 UTC, lizziel commented on run/shared/settings/geosit/geosit.preprocessed_ll.txt
> +RUNDIR_MET_EXT='nc'
Why is the preprocessed lat-lon extension nc rather than nc4? It doesn't really matter, but it seems like we should have consistency between GEOS-IT and MERRA2 processed files, and nc4 is more descriptive than nc.

2025-01-09 15:38 UTC, lizziel commented on run/shared/settings/geosit/geosit.preprocessed_wind_cs.txt
> +PS1     hPa     N Y  0        none none PS  ./MetDir/%y4/%m2/GEOSIT.%y4%m2%d2.I3.05x0625.nc
We hard-code the pressure unit and scaling in these wind and mass flux files per meteorology type. Why then do we also define RUNDIR_MET_PRES_UNIT and RUNDIR_MET_PRES_SCALE in the raw and processed text files? If these are not used then we should delete.

2025-01-09 15:38 UTC, lizziel commented on run/shared/settings/geosit/geosit.raw_cs.txt
> +RUNDIR_MET_PRES_UNIT='Pa'
See comment above.

2025-01-09 21:18 UTC, yuanjianz commented on run/shared/settings/geosit/geosit.preprocessed_ll.txt
> +RUNDIR_MET_EXT='nc'
It is because the file extension name for MERRA2 is nc4 while for GEOSIT it is nc. In this case, GEOSFP and GEOSIT are both in the extension nc.

2025-01-09 21:19 UTC, yuanjianz commented on run/shared/settings/geosit/geosit.preprocessed_wind_cs.txt
> +PS1     hPa     N Y  0        none none PS  ./MetDir/%y4/%m2/GEOSIT.%y4%m2%d2.I3.05x0625.nc
Yeah, I don't see why there is RUNDIR_MET_PRES_UNIT and RUNDIR_MET_PRES_SCALE left given they are not used anyway.

2025-01-10 14:39 UTC, lizziel commented on run/shared/settings/geosit/geosit.preprocessed_ll.txt
> +RUNDIR_MET_EXT='nc'
Okay, this is more a general question for whoever does the processing. Whether we give it nc or nc4 is based on our processing code so is set by us. No problem it's nc but if we get a future meteorology dataset we should use nc4.

2025-01-16 18:34 UTC, lizziel commented
@yuanjianz, if you are okay with it I will make the requested changes to the branch so that we can merge it in.

2025-01-17 19:13 UTC, yuanjianz commented
Sure, thanks @lizziel, sorry for being unresponsive recently.

2025-01-17 21:55 UTC, lizziel commented
No worries, I will make the updates next week.

2025-01-23 16:04 UTC, lizziel commented
I am changing the target to 14.5.2 since there isn't a reason to wait for 14.6.0 for this update.

2025-01-23 16:09 UTC, lizziel commented on CHANGELOG.md
> +- Added createRunDir for processed cubed-sphere GEOS-IT meteorology
Done

2025-01-23 16:09 UTC, lizziel commented on run/shared/settings/geosit/geosit.preprocessed_wind_cs.txt
> +PS1     hPa     N Y  0        none none PS  ./MetDir/%y4/%m2/GEOSIT.%y4%m2%d2.I3.05x0625.nc
Done

2025-01-23 16:29 UTC, lizziel approved these changes

2025-01-23 16:30 UTC, lizziel commented
@yantosca, I added you as a reviewer since I just pushed a bunch of updates to this PR. I have integration tests running now.

2025-01-23 19:23 UTC, yantosca approved these changes
Thanks @lizziel!  Looks good to merge.

2025-01-30 18:13 UTC, merged