Ch4 pseudo fluxes
geoschem/geos-chem pull request #674
Opened 2021-03-26 10:52 UTC by rgryan92

Activating pre-existing code in GEOS-Chem to read and write methane pseudo fluxes

2021-09-14 17:41 UTC, msulprizio commented
This pull request impacts several blocks of code for `MODEL_GEOS`. I would defer to @lizziel on reviewing and merging these changes.

2022-03-01 19:27 UTC, lizziel commented on GeosCore/hcoi_gc_diagn_include.H
> +  INTEGER, PARAMETER :: CATEGORY_ROCKET        = 6
Is this change relevant to CH4 pseudo flux diagnostics?

2022-03-01 19:31 UTC, lizziel requested changes

2022-03-01 19:31 UTC, lizziel commented on GeosCore/hcoi_gc_diagn_include.H
> +  INTEGER, PARAMETER :: CATEGORY_ROCKET        = 6
Is this change relevant to the CH4 pseudo flux update?

2022-03-01 19:31 UTC, lizziel commented on GeosUtil/gc_grid_mod.F90
> +       State_Grid%MaxChemLev  = State_Grid%NZ
Could explain why you made this change?

2022-03-01 19:31 UTC, lizziel commented on Headers/state_diag_mod.F90
> +!#ifdef MODEL_GEOS
This change includes adding fields beyond what is needed for CH4 pseudo flux diagnostics. Is that intentional?

2022-03-01 19:31 UTC, lizziel commented on KPP/Standard/gckpp.map
> +! Time                 : Tue Aug 25 12:43:27 2020
The KPP file changes indicate your base is out-of-date with current dev. Could you rebase?

2022-03-01 19:31 UTC, lizziel commented on log
> +make[1]: Entering directory `/lustre/home/ucfaea1/Models/GEOS-Chem/Codes/Code.12.9.3/GeosCore'
I don't think this file was intended to be included in the PR.

2022-03-01 19:31 UTC, lizziel commented on run/GEOS/CodeDir
> +/home/ucfaea1/Models/GEOS-Chem/Codes/Code.12.9.3
Did you intend to change the run/GEOS files?

2022-03-02 16:03 UTC, lizziel commented
Hi @rgryan92, I discussed this with Christoph Keller and he approved bringing it into the standard version. GMAO has been outputting it regularly in their real-time system and it seems to work fine. Rather than have you rebase I can go ahead and make a new PR with the modifications to take the diagnostic out of the MODEL_GEOS block.

2022-03-02 16:32 UTC, closed without merging